// Data extracted 1:1 from the Claude Design source (Table for One.dc.html).

export const recipes = {
      'greek-yogurt-bowl':{id:'greek-yogurt-bowl',name:'Greek Yogurt & Berry Bowl',cuisine:'',tagline:'Breakfast · no cook',cost:2.5,protein:25,timeMin:5,ingredients:[{item:'Greek yogurt',qty:'1 cup'},{item:'Blueberries',qty:'½ cup'},{item:'Honey',qty:'1 tsp'},{item:'Almonds',qty:'handful'},{item:'Chia seeds',qty:'1 tsp'}],steps:['Spoon the yogurt into a bowl.','Top with berries, almonds and chia.','Finish with a drizzle of honey.'],note:'A five-minute, 25g-protein start. Swap in whatever fruit needs using up.'},
      'mango-fruit-bowl':{id:'mango-fruit-bowl',name:'Mango & Passion Fruit Bowl',cuisine:'',tagline:'Breakfast · no cook',cost:2.8,protein:22,timeMin:6,ingredients:[{item:'Mango',qty:'1'},{item:'Greek yogurt',qty:'¾ cup'},{item:'Banana',qty:'½'},{item:'Almonds',qty:'handful'},{item:'Honey',qty:'1 tsp'}],steps:['Cube the mango and slice the banana.','Layer over yogurt in a bowl.','Scatter almonds and drizzle honey.'],note:'Ripe tropical fruit plus 22g protein — sunshine in a bowl.'},
      'overnight-oats':{id:'overnight-oats',name:'Peanut Butter Overnight Oats',cuisine:'',tagline:'Breakfast · make-ahead',cost:1.8,protein:20,timeMin:5,ingredients:[{item:'Rolled oats',qty:'½ cup'},{item:'Milk',qty:'½ cup'},{item:'Peanut butter',qty:'1 tbsp'},{item:'Banana',qty:'½'},{item:'Chia seeds',qty:'1 tsp'}],steps:['Combine oats, milk and chia in a jar.','Stir through peanut butter and sliced banana.','Chill overnight; eat straight from the jar.'],note:'Build three jars at once and breakfast is sorted for half the week.'},
      'veggie-omelette':{id:'veggie-omelette',name:'Spinach & Feta Omelette',cuisine:'',tagline:'Breakfast · 12 min',cost:2.2,protein:24,timeMin:12,ingredients:[{item:'Eggs',qty:'3'},{item:'Spinach',qty:'1 handful'},{item:'Feta',qty:'30g'},{item:'Cherry tomatoes',qty:'4'}],steps:['Wilt the spinach in a hot pan.','Pour in whisked eggs; scatter tomato and feta.','Fold over and slide onto the plate.'],note:'Three eggs quietly deliver 24g of protein before you leave the house.'},
      'protein-smoothie':{id:'protein-smoothie',name:'Green Protein Smoothie',cuisine:'',tagline:'Breakfast · blitz & go',cost:3.0,protein:32,timeMin:5,ingredients:[{item:'Greek yogurt',qty:'½ cup'},{item:'Banana',qty:'1'},{item:'Spinach',qty:'1 handful'},{item:'Blueberries',qty:'½ cup'},{item:'Milk',qty:'1 cup'},{item:'Whey protein',qty:'1 scoop'}],steps:['Add everything to the blender.','Blend until completely smooth.','Pour into a bottle and run.'],note:"The spinach disappears — you'll only taste berries and banana."},
      'cottage-toast':{id:'cottage-toast',name:'Cottage Cheese Toast & Egg',cuisine:'',tagline:'Breakfast · 10 min',cost:2.4,protein:26,timeMin:10,ingredients:[{item:'Cottage cheese',qty:'½ cup'},{item:'Sourdough bread',qty:'1 slice'},{item:'Tomato',qty:'½'},{item:'Eggs',qty:'1'}],steps:['Toast the sourdough.','Fry or poach the egg.','Pile on cottage cheese, tomato and the egg.'],note:'Cottage cheese is back in fashion for a reason — cheap, creamy, 26g protein.'},
      'githeri':{id:'githeri',name:'Githeri (Maize & Beans)',cuisine:'Kenyan',tagline:'Lunch · one pot',cost:2.8,protein:24,timeMin:35,ingredients:[{item:'Maize (canned)',qty:'1 can'},{item:'Kidney beans',qty:'1 can'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Carrot',qty:'1'},{item:'Cumin',qty:'1 tsp'}],steps:['Fry onion until soft, add chopped tomato and carrot.','Tip in drained maize and beans with a splash of water.','Season and simmer 20 minutes until thick.'],note:'The everyday Kenyan comfort bowl — hearty, cheap and freezes beautifully.'},
      'nyama-choma':{id:'nyama-choma',name:'Nyama Choma & Kachumbari',cuisine:'Kenyan',tagline:'Dinner · grill night',cost:7.0,protein:46,timeMin:35,ingredients:[{item:'Beef steak',qty:'250g'},{item:'Lemon',qty:'½'},{item:'Tomato',qty:'1'},{item:'Red onion',qty:'½'},{item:'Cilantro',qty:'handful'},{item:'Chili',qty:'1'}],steps:['Season the beef with salt and grill or pan-sear to your liking.','Toss tomato, onion, cilantro, chili and lemon for kachumbari.','Rest the meat, slice, and serve with the fresh salad.'],note:'A weekend treat for one — a single good steak, charred and rested, needs nothing more than kachumbari.'},
      'jollof-chicken':{id:'jollof-chicken',name:'Jollof Rice & Chicken',cuisine:'Nigerian',tagline:'Dinner · big batch',cost:5.5,protein:42,timeMin:45,ingredients:[{item:'Rice',qty:'1 cup'},{item:'Chicken thighs',qty:'3'},{item:'Tomato',qty:'3'},{item:'Bell pepper',qty:'1'},{item:'Onion',qty:'1'},{item:'Tomato paste',qty:'2 tbsp'}],steps:['Blend tomato, pepper and onion; fry down with tomato paste.','Brown the chicken, then add rice and stock to the sauce.','Cover and steam 25 min until the rice is smoky and tender.'],note:'The party classic, scaled for one cook and three meals. Day-two jollof is even better.'},
      'egusi-soup':{id:'egusi-soup',name:'Egusi Soup & Spinach',cuisine:'Nigerian',tagline:'Dinner · rich & filling',cost:6.0,protein:38,timeMin:40,ingredients:[{item:'Ground egusi (melon seeds)',qty:'½ cup'},{item:'Spinach',qty:'2 handfuls'},{item:'Chicken thighs',qty:'2'},{item:'Palm oil',qty:'2 tbsp'},{item:'Onion',qty:'1'},{item:'Stock cube',qty:'1'}],steps:['Bloom onion in palm oil, add the egusi paste and fry.','Add chicken and stock; simmer until thickened.','Stir in spinach at the end and serve with rice.'],note:'Nutty, protein-packed and deeply savoury — a single pot that eats like a feast.'},
      'coconut-fish-curry':{id:'coconut-fish-curry',name:'Samaki wa Nazi (Coconut Fish Curry)',cuisine:'Swahili',tagline:'Dinner · 25 min',cost:6.5,protein:36,timeMin:25,ingredients:[{item:'White fish fillet',qty:'1'},{item:'Coconut milk',qty:'½ can'},{item:'Tomato',qty:'2'},{item:'Onion',qty:'½'},{item:'Lime',qty:'1'},{item:'Cilantro',qty:'handful'}],steps:['Soften onion and tomato in a pan.','Pour in coconut milk and bring to a gentle simmer.','Slide in the fish, cook 8 min, finish with lime and cilantro.'],note:'Coastal Swahili comfort — creamy coconut, bright lime, ready in under half an hour.'},
      'pilau':{id:'pilau',name:'Beef Pilau',cuisine:'Swahili',tagline:'Dinner · batch it',cost:5.0,protein:34,timeMin:45,ingredients:[{item:'Rice',qty:'1 cup'},{item:'Beef steak',qty:'200g'},{item:'Onion',qty:'1'},{item:'Pilau masala',qty:'1 tbsp'},{item:'Garlic',qty:'2 cloves'},{item:'Stock cube',qty:'1'}],steps:['Caramelise onion deeply, add cubed beef and brown.','Stir in pilau masala and garlic until fragrant.','Add rice and stock; cover and steam 25 minutes.'],note:'One spiced pot of Swahili pilau makes lunch and dinner sing all week.'},
      'chicken-tikka':{id:'chicken-tikka',name:'Chicken Tikka Masala',cuisine:'Indian',tagline:'Dinner · batch it',cost:6.0,protein:44,timeMin:40,ingredients:[{item:'Chicken breast',qty:'2'},{item:'Yogurt',qty:'½ cup'},{item:'Tomato',qty:'3'},{item:'Onion',qty:'1'},{item:'Garam masala',qty:'1 tbsp'},{item:'Rice',qty:'½ cup'}],steps:['Marinate chicken in yogurt and garam masala, then sear.','Simmer a tomato-onion sauce and stir the chicken back in.','Serve over rice; save half for tomorrow.'],note:'Cook two breasts — one dinner tonight, a ready-made lunch tomorrow.'},
      'chana-masala':{id:'chana-masala',name:'Chana Masala',cuisine:'Indian',tagline:'Lunch · freezer-friendly',cost:3.2,protein:22,timeMin:30,ingredients:[{item:'Chickpeas (canned)',qty:'1 can'},{item:'Tomato',qty:'2'},{item:'Onion',qty:'1'},{item:'Ginger',qty:'1 thumb'},{item:'Garam masala',qty:'1 tbsp'},{item:'Garlic',qty:'2 cloves'}],steps:['Fry onion, ginger and garlic to a paste.','Add tomato and garam masala; cook down.','Tip in chickpeas and simmer 15 minutes.'],note:'A meat-free, budget hero that portions and freezes for pennies a bowl.'},
      'matoke-groundnut':{id:'matoke-groundnut',name:'Matoke in Groundnut Sauce',cuisine:'Ugandan',tagline:'Dinner · one pot',cost:4.2,protein:26,timeMin:40,ingredients:[{item:'Green banana (matoke)',qty:'4'},{item:'Peanut butter',qty:'2 tbsp'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Eggs',qty:'2'}],steps:['Peel and simmer the matoke until just tender.','Make a groundnut sauce with onion, tomato and peanut butter.','Fold the matoke through; top with boiled egg for protein.'],note:'Uganda\u2019s beloved steamed banana, silky in a nutty groundnut sauce.'},
      'luwombo-chicken':{id:'luwombo-chicken',name:'Chicken Luwombo',cuisine:'Ugandan',tagline:'Dinner · slow & tender',cost:5.5,protein:40,timeMin:50,ingredients:[{item:'Chicken thighs',qty:'2'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Bell pepper',qty:'1'},{item:'Peanut butter',qty:'1 tbsp'},{item:'Stock cube',qty:'1'}],steps:['Brown chicken with onion, pepper and tomato.','Loosen a spoon of groundnut into the sauce.','Cover low and steam 30 min until falling-tender.'],note:'Traditionally steamed in banana leaves — this stovetop version keeps the deep, comforting flavour.'},
      'spaghetti-bolognese':{id:'spaghetti-bolognese',name:'Spaghetti Bolognese',cuisine:'Italian',tagline:'Dinner · batch it',cost:4.8,protein:38,timeMin:35,ingredients:[{item:'Spaghetti',qty:'80g'},{item:'Ground beef',qty:'200g'},{item:'Tomato',qty:'3'},{item:'Onion',qty:'1'},{item:'Carrot',qty:'1'},{item:'Parmesan',qty:'2 tbsp'}],steps:['Soften onion and carrot, brown the beef.','Add tomato and simmer 20 min into a rich ragù.','Toss with cooked spaghetti and grate over parmesan.'],note:'Make a double batch of ragù — it turns into three different dinners with zero effort.'},
      'pesto-chicken-pasta':{id:'pesto-chicken-pasta',name:'Pesto Chicken Pasta',cuisine:'Italian',tagline:'Dinner · 20 min',cost:5.0,protein:38,timeMin:20,ingredients:[{item:'Pasta',qty:'80g'},{item:'Pesto',qty:'2 tbsp'},{item:'Chicken breast',qty:'1'},{item:'Cherry tomatoes',qty:'6'},{item:'Parmesan',qty:'2 tbsp'}],steps:['Boil the pasta.','Toss with pesto, sliced chicken and tomato.','Finish with parmesan.'],note:'An easy Sunday plate — measure 80g of dry pasta so cooking-for-one stays cooking-for-one.'},
      'sukuma-ugali':{id:'sukuma-ugali',name:'Sukuma Wiki na Ugali',cuisine:'Kenyan',tagline:'Lunch · everyday',cost:2.4,protein:18,timeMin:25,ingredients:[{item:'Collard greens',qty:'2 handfuls'},{item:'Cornmeal (ugali)',qty:'1 cup'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'},{item:'Eggs',qty:'2'}],steps:['Whisk cornmeal into boiling water, stirring until it pulls into a stiff dough — that\u2019s ugali.','Soften onion and tomato in a pan, then wilt the shredded collard greens through.','Fry the eggs and serve alongside for extra protein.'],note:'Kenya\u2019s everyday plate — a stiff cornmeal ugali against peppery greens, built for pennies.'},
      'mukimo-beef':{id:'mukimo-beef',name:'Mukimo & Beef Stew',cuisine:'Kenyan',tagline:'Dinner · batch it',cost:5.2,protein:34,timeMin:45,ingredients:[{item:'Potato',qty:'3'},{item:'Green peas',qty:'½ cup'},{item:'Corn kernels',qty:'½ cup'},{item:'Beef stew meat',qty:'200g'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'}],steps:['Boil potato, peas and corn together, then mash into mukimo.','Brown the beef with onion and tomato; simmer into a thick stew.','Serve the mash with a well of stew spooned over the top.'],note:'Kikuyu comfort food — a mound of smoky mashed veg with a rich beef stew.'},
      'mandazi-chai':{id:'mandazi-chai',name:'Mandazi & Kenyan Chai',cuisine:'Kenyan',tagline:'Breakfast · semi-sweet',cost:1.6,protein:10,timeMin:20,ingredients:[{item:'Flour',qty:'1 cup'},{item:'Sugar',qty:'2 tbsp'},{item:'Coconut milk',qty:'¼ cup'},{item:'Cardamom',qty:'pinch'},{item:'Milk',qty:'1 cup'},{item:'Tea leaves',qty:'1 tsp'}],steps:['Mix flour, sugar, coconut milk and cardamom into a soft dough; rest 20 minutes.','Shape into triangles and fry until golden and puffed.','Boil milk with tea leaves and a little ginger for the chai.'],note:'Pillowy fried dough dunked in spiced milky chai — a slow Kenyan morning, any day of the week.'},
      'kenyan-uji':{id:'kenyan-uji',name:'Uji (Spiced Millet Porridge)',cuisine:'Kenyan',tagline:'Breakfast · warm & filling',cost:1.4,protein:12,timeMin:15,ingredients:[{item:'Millet flour',qty:'½ cup'},{item:'Milk',qty:'1 cup'},{item:'Cinnamon',qty:'pinch'},{item:'Sugar',qty:'1 tbsp'}],steps:['Whisk millet flour with a little cold water until smooth.','Bring to a simmer, stirring, until thickened.','Loosen with milk, sweeten, and dust with cinnamon.'],note:'A gently spiced porridge — the breakfast that fuels Kenyan mornings before the day gets going.'},
      'mishkaki-skewers':{id:'mishkaki-skewers',name:'Mishkaki Skewers & Kachumbari',cuisine:'Swahili',tagline:'Dinner · grill night',cost:6.2,protein:40,timeMin:30,ingredients:[{item:'Beef steak',qty:'250g'},{item:'Lemon',qty:'1'},{item:'Garlic',qty:'2 cloves'},{item:'Tomato',qty:'1'},{item:'Red onion',qty:'½'},{item:'Cilantro',qty:'handful'}],steps:['Cube the beef and marinate in lemon, garlic and a little oil.','Thread onto skewers and grill, turning until charred.','Serve with a quick kachumbari of tomato, onion and cilantro.'],note:'East African coast street food — smoky skewers off the grill, sharpened with lemon and chili.'},
      'maharagwe-nazi':{id:'maharagwe-nazi',name:'Maharagwe ya Nazi (Coconut Beans) & Chapati',cuisine:'Swahili',tagline:'Lunch · freezer-friendly',cost:2.6,protein:20,timeMin:35,ingredients:[{item:'Kidney beans',qty:'1 can'},{item:'Coconut milk',qty:'½ can'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Chapati',qty:'2'}],steps:['Soften onion and tomato, then stir in coconut milk.','Add the beans and simmer until the sauce thickens.','Serve scooped up with warm chapati.'],note:'Creamy coconut beans — a coastal staple that costs pennies and freezes perfectly.'},
      'vitumbua-chai':{id:'vitumbua-chai',name:'Vitumbua & Ginger Chai',cuisine:'Swahili',tagline:'Breakfast · coconut & rice',cost:1.8,protein:9,timeMin:25,ingredients:[{item:'Rice flour',qty:'1 cup'},{item:'Coconut milk',qty:'½ cup'},{item:'Sugar',qty:'2 tbsp'},{item:'Yeast',qty:'½ tsp'},{item:'Milk',qty:'1 cup'},{item:'Ginger',qty:'1 thumb'}],steps:['Batter rice flour, coconut milk, sugar and yeast; let it bubble for an hour.','Fry spoonfuls in a small pan until golden on both sides.','Simmer milk with grated ginger for the chai.'],note:'Zanzibar\u2019s little coconut-rice pancakes, crisp-edged and just sweet enough.'},
      'bajia-chutney':{id:'bajia-chutney',name:'Bajia & Tamarind Chutney',cuisine:'Swahili',tagline:'Breakfast · spiced & fried',cost:2.0,protein:8,timeMin:25,ingredients:[{item:'Potato',qty:'2'},{item:'Chickpea flour',qty:'½ cup'},{item:'Turmeric',qty:'pinch'},{item:'Chili',qty:'1'},{item:'Tamarind',qty:'1 tbsp'}],steps:['Slice potato thin; dip in a spiced chickpea-flour batter.','Fry until deep golden and crisp.','Serve with a quick tamarind chutney for dipping.'],note:'A Swahili-Indian coastal handshake — crisp fritters with a tangy-sweet tamarind dip.'},
      'efo-riro':{id:'efo-riro',name:'Efo Riro (Spinach & Beef Stew)',cuisine:'Nigerian',tagline:'Lunch · rich & filling',cost:5.4,protein:32,timeMin:35,ingredients:[{item:'Spinach',qty:'2 handfuls'},{item:'Beef stew meat',qty:'150g'},{item:'Bell pepper',qty:'1'},{item:'Onion',qty:'1'},{item:'Palm oil',qty:'2 tbsp'},{item:'Stock cube',qty:'1'}],steps:['Blend pepper and onion; fry down in palm oil until deep red.','Add beef and stock; simmer until tender.','Stir in spinach just before serving with rice.'],note:'Deep, peppery and green — a Nigerian stew that tastes better the day after.'},
      'moi-moi-plantain':{id:'moi-moi-plantain',name:'Moi Moi & Fried Plantain',cuisine:'Nigerian',tagline:'Lunch · steamed & filling',cost:3.0,protein:18,timeMin:40,ingredients:[{item:'Black-eyed peas',qty:'1 cup'},{item:'Bell pepper',qty:'1'},{item:'Onion',qty:'½'},{item:'Eggs',qty:'1'},{item:'Plantain',qty:'1'}],steps:['Blend soaked black-eyed peas with pepper and onion into a smooth batter.','Pour into cups with a boiled egg pressed in; steam 35 minutes.','Fry plantain slices until caramelised and serve alongside.'],note:'Steamed bean pudding, sweet plantain on the side — filling for almost nothing.'},
      'akara-pap':{id:'akara-pap',name:'Akara & Pap',cuisine:'Nigerian',tagline:'Breakfast · fritters & porridge',cost:2.0,protein:16,timeMin:25,ingredients:[{item:'Black-eyed peas',qty:'1 cup'},{item:'Onion',qty:'¼'},{item:'Chili',qty:'1'},{item:'Cornmeal (pap)',qty:'½ cup'},{item:'Sugar',qty:'1 tbsp'}],steps:['Blend soaked peas with onion and chili into a fluffy batter; fry spoonfuls until golden.','Whisk fine cornmeal into simmering water until smooth for the pap.','Sweeten the pap lightly and serve hot with the akara.'],note:'Crisp bean fritters against silky corn porridge — Lagos breakfast, sorted.'},
      'yam-egg-sauce':{id:'yam-egg-sauce',name:'Yam & Egg Sauce',cuisine:'Nigerian',tagline:'Breakfast · hearty',cost:2.4,protein:18,timeMin:20,ingredients:[{item:'Yam',qty:'300g'},{item:'Eggs',qty:'2'},{item:'Tomato',qty:'1'},{item:'Onion',qty:'½'},{item:'Bell pepper',qty:'½'}],steps:['Boil peeled yam chunks until tender.','Scramble eggs with tomato, onion and pepper into a loose sauce.','Serve the sauce spooned over the boiled yam.'],note:'A Nigerian breakfast staple — starchy yam meeting a peppery egg sauce.'},
      'beef-posho':{id:'beef-posho',name:'Beef Stew & Posho',cuisine:'Ugandan',tagline:'Dinner · everyday',cost:4.8,protein:30,timeMin:40,ingredients:[{item:'Beef stew meat',qty:'200g'},{item:'Cornmeal (posho)',qty:'1 cup'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Carrot',qty:'1'}],steps:['Brown the beef with onion, tomato and carrot; simmer until tender.','Whisk cornmeal into boiling water, stirring to a stiff posho.','Serve the posho alongside a ladle of stew.'],note:'Uganda\u2019s daily plate — stiff cornmeal posho next to a simple, tomatoey beef stew.'},
      'doodo-groundnut':{id:'doodo-groundnut',name:'Doodo & Groundnut Sauce',cuisine:'Ugandan',tagline:'Lunch · veg & budget',cost:2.4,protein:16,timeMin:30,ingredients:[{item:'Amaranth greens (doodo)',qty:'2 handfuls'},{item:'Peanut butter',qty:'2 tbsp'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'},{item:'Eggs',qty:'1'}],steps:['Simmer chopped greens with onion and tomato until soft.','Loosen peanut butter with a little water and stir through.','Top with a boiled egg for extra protein.'],note:'Leafy, nutty and quietly filling — a budget-hero Ugandan lunch.'},
      'rolex-wrap':{id:'rolex-wrap',name:'Rolex (Chapati-Rolled Omelette)',cuisine:'Ugandan',tagline:'Breakfast · street food',cost:1.8,protein:16,timeMin:12,ingredients:[{item:'Chapati',qty:'1'},{item:'Eggs',qty:'2'},{item:'Cabbage',qty:'handful'},{item:'Tomato',qty:'½'},{item:'Onion',qty:'¼'}],steps:['Whisk eggs with shredded cabbage, tomato and onion; fry into a flat omelette.','Warm the chapati in the same pan.','Lay the omelette on the chapati and roll it tight.'],note:'Uganda\u2019s iconic street breakfast, "rolled" — eggs and chapati, eaten on the move.'},
      'katogo':{id:'katogo',name:'Katogo (Matoke & Beef Breakfast Stew)',cuisine:'Ugandan',tagline:'Breakfast · hearty stew',cost:3.4,protein:22,timeMin:30,ingredients:[{item:'Green banana (matoke)',qty:'3'},{item:'Beef stew meat',qty:'100g'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'},{item:'Stock cube',qty:'1'}],steps:['Brown the beef with onion and tomato.','Add peeled matoke and a splash of stock; cover and simmer until soft.','Mash slightly so the matoke soaks up the stew.'],note:'A one-pot breakfast stew, hearty enough to carry you to dinner.'},
      'dal-tadka':{id:'dal-tadka',name:'Dal Tadka & Jeera Rice',cuisine:'Indian',tagline:'Lunch · everyday comfort',cost:2.4,protein:18,timeMin:30,ingredients:[{item:'Red lentils',qty:'¾ cup'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'},{item:'Garlic',qty:'2 cloves'},{item:'Cumin',qty:'1 tsp'},{item:'Rice',qty:'½ cup'}],steps:['Simmer lentils until soft and starting to break down.','Fry garlic, cumin and onion in a little oil and pour over as a tempering.','Serve with cumin rice on the side.'],note:'The dish every Indian kitchen makes without a recipe — soft lentils, a sizzling tempering on top.'},
      'palak-paneer':{id:'palak-paneer',name:'Palak Paneer & Roti',cuisine:'Indian',tagline:'Dinner · batch it',cost:5.6,protein:26,timeMin:35,ingredients:[{item:'Spinach',qty:'2 handfuls'},{item:'Paneer',qty:'150g'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'},{item:'Garlic',qty:'2 cloves'},{item:'Roti',qty:'2'}],steps:['Blanch and blend the spinach into a smooth puree.','Fry onion, garlic and tomato, then stir in the spinach puree.','Fold in cubed paneer and warm through; serve with roti.'],note:'Silky spiced spinach with soft paneer — a vegetarian dinner that never feels like a compromise.'},
      'veg-upma':{id:'veg-upma',name:'Vegetable Upma',cuisine:'Indian',tagline:'Breakfast · semolina',cost:1.6,protein:10,timeMin:15,ingredients:[{item:'Semolina',qty:'¾ cup'},{item:'Carrot',qty:'1'},{item:'Onion',qty:'½'},{item:'Mustard seeds',qty:'½ tsp'},{item:'Cumin',qty:'½ tsp'}],steps:['Toast semolina dry until fragrant; set aside.','Fry mustard seeds, onion and diced carrot until soft.','Stir in the semolina with hot water until fluffy.'],note:'A savoury semolina porridge — ready before the coffee finishes brewing.'},
      'besan-chilla':{id:'besan-chilla',name:'Besan Chilla (Chickpea Pancake)',cuisine:'Indian',tagline:'Breakfast · savoury',cost:1.8,protein:16,timeMin:12,ingredients:[{item:'Chickpea flour',qty:'1 cup'},{item:'Onion',qty:'¼'},{item:'Tomato',qty:'¼'},{item:'Cumin',qty:'½ tsp'},{item:'Chili',qty:'1'}],steps:['Whisk chickpea flour with water into a smooth, pourable batter.','Stir in chopped onion, tomato, chili and cumin.','Ladle onto a hot griddle and cook both sides until golden.'],note:'A savoury protein pancake from batter you already have in the cupboard.'},
      'minestrone-crostini':{id:'minestrone-crostini',name:'Minestrone & Parmesan Crostini',cuisine:'Italian',tagline:'Lunch · freezer-friendly',cost:3.4,protein:16,timeMin:35,ingredients:[{item:'Kidney beans',qty:'1 can'},{item:'Carrot',qty:'1'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Pasta',qty:'½ cup'},{item:'Parmesan',qty:'2 tbsp'}],steps:['Soften onion and carrot, then add tomato and a splash of stock.','Simmer in the beans and small pasta until tender.','Ladle into a bowl and finish with parmesan crostini.'],note:'A big pot of Italian vegetable soup — the kind that gets better on day two.'},
      'chicken-parmigiana':{id:'chicken-parmigiana',name:'Chicken Parmigiana & Greens',cuisine:'Italian',tagline:'Dinner · Sunday effort',cost:6.4,protein:42,timeMin:40,ingredients:[{item:'Chicken breast',qty:'1'},{item:'Breadcrumbs',qty:'½ cup'},{item:'Parmesan',qty:'3 tbsp'},{item:'Tomato',qty:'2'},{item:'Mozzarella',qty:'50g'},{item:'Spinach',qty:'1 handful'}],steps:['Crumb the chicken breast and pan-fry until golden.','Top with tomato sauce, mozzarella and parmesan; melt under the grill.','Serve with a handful of wilted greens.'],note:'Crisp, cheesy, and worth the extra ten minutes on a slower night.'},
      'ricotta-toast':{id:'ricotta-toast',name:'Ricotta Toast with Honey & Walnuts',cuisine:'Italian',tagline:'Breakfast · no cook',cost:2.4,protein:14,timeMin:6,ingredients:[{item:'Sourdough bread',qty:'1 slice'},{item:'Ricotta',qty:'½ cup'},{item:'Honey',qty:'1 tsp'},{item:'Walnuts',qty:'handful'}],steps:['Toast the sourdough.','Spread thickly with ricotta.','Drizzle honey and scatter walnuts over the top.'],note:'As close to dessert as breakfast gets — five minutes, no stove needed.'},
      'uova-pomodoro':{id:'uova-pomodoro',name:'Uova al Pomodoro (Eggs in Tomato Sauce)',cuisine:'Italian',tagline:'Breakfast · 15 min',cost:2.2,protein:20,timeMin:15,ingredients:[{item:'Eggs',qty:'2'},{item:'Tomato',qty:'3'},{item:'Garlic',qty:'1 clove'},{item:'Parmesan',qty:'1 tbsp'},{item:'Sourdough bread',qty:'1 slice'}],steps:['Simmer crushed tomato with garlic until it reduces to a thick sauce.','Crack in the eggs and cover until just set.','Finish with parmesan and mop up with toasted sourdough.'],note:'A rustic breakfast — eggs poached right in a garlicky tomato sauce.'},
      'omena-ugali':{id:'omena-ugali',name:'Omena na Ugali',cuisine:'Kenyan',tagline:'Lunch · Luo classic',cost:1.6,protein:22,timeMin:25,ingredients:[{item:'Omena (dried silverfish)',qty:'1 cup'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Cornmeal (ugali)',qty:'1 cup'}],steps:['Rinse and soak the dried omena briefly.','Fry onion and tomato, then simmer the omena through for 10 minutes.','Serve with freshly cooked ugali.'],note:'A Luo lakeside staple — sun-dried silverfish simmered down, about as cheap as protein gets.'},
      'muthokoi':{id:'muthokoi',name:'Muthokoi (Maize & Pigeon Peas)',cuisine:'Kenyan',tagline:'Lunch · Kamba, budget',cost:1.4,protein:16,timeMin:35,ingredients:[{item:'Dehulled maize (muthokoi)',qty:'1 cup'},{item:'Pigeon peas',qty:'½ cup'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'}],steps:['Boil the dehulled maize and pigeon peas together until tender.','Fry onion and tomato separately, then fold through.','Simmer 10 more minutes to bring it together.'],note:'A Kamba classic — dehulled maize and pigeon peas, simmered soft. Filling for pennies.'},
      'ingokho-stew':{id:'ingokho-stew',name:'Ingokho (Luhya Chicken Stew)',cuisine:'Kenyan',tagline:'Dinner · Luhya, slow-cooked',cost:4.6,protein:36,timeMin:45,ingredients:[{item:'Chicken (indigenous)',qty:'½ bird'},{item:'Onion',qty:'2'},{item:'Tomato',qty:'2'},{item:'Garlic',qty:'2 cloves'},{item:'Cilantro',qty:'handful'}],steps:['Brown the chicken pieces with onion and garlic.','Add tomato and a splash of water; simmer low until tender.','Finish with cilantro and serve with ugali or rice.'],note:'Luhya kitchens are known for this slow chicken stew — free-range bird, deeply savoury, worth the simmer.'},
      'mursik-sweet-potato':{id:'mursik-sweet-potato',name:'Mursik & Sweet Potato',cuisine:'Kenyan',tagline:'Breakfast · Kalenjin',cost:1.6,protein:10,timeMin:15,ingredients:[{item:'Mursik (fermented milk)',qty:'1 cup'},{item:'Sweet potato',qty:'1'}],steps:['Boil the sweet potato until tender.','Peel and slice.','Serve alongside a cup of mursik.'],note:'A Kalenjin morning ritual — tangy fermented milk, traditionally aged in a soot-lined gourd, next to boiled sweet potato.'},
      'amala-ewedu':{id:'amala-ewedu',name:'Amala & Ewedu',cuisine:'Nigerian',tagline:'Lunch · Yoruba',cost:2.6,protein:18,timeMin:30,ingredients:[{item:'Yam flour (amala)',qty:'1 cup'},{item:'Jute leaves (ewedu)',qty:'2 handfuls'},{item:'Locust beans',qty:'1 tbsp'},{item:'Stock cube',qty:'1'}],steps:['Whisk yam flour into boiling water until smooth and stretchy — that\u2019s amala.','Blend jute leaves with a little water, then simmer with locust beans and stock.','Serve the amala with the ewedu spooned over.'],note:'A Yoruba lunchtime staple — earthy amala against a silky, slightly ropy ewedu soup.'},
      'ofe-nsala':{id:'ofe-nsala',name:'Ofe Nsala (White Soup)',cuisine:'Nigerian',tagline:'Dinner · Igbo, white soup',cost:5.8,protein:34,timeMin:40,ingredients:[{item:'White fish fillet',qty:'1'},{item:'Yam',qty:'200g'},{item:'Ground crayfish',qty:'1 tbsp'},{item:'Chili',qty:'1'},{item:'Onion',qty:'1'}],steps:['Simmer fish gently in seasoned water until just cooked; set aside.','Grate yam and stir into the broth to thicken — this is what makes it "white soup."','Return the fish, add crayfish and chili, and simmer 10 more minutes.'],note:'An Igbo delicacy — no palm oil, just a pepper-bright broth thickened with grated yam.'},
      'tuwo-kuka':{id:'tuwo-kuka',name:'Tuwo Shinkafa & Miyan Kuka',cuisine:'Nigerian',tagline:'Lunch · Hausa, budget',cost:2.2,protein:14,timeMin:30,ingredients:[{item:'Rice',qty:'1 cup'},{item:'Baobab leaf powder (kuka)',qty:'2 tbsp'},{item:'Dried fish',qty:'30g'},{item:'Onion',qty:'1'},{item:'Stock cube',qty:'1'}],steps:['Cook rice soft and pound smooth into tuwo.','Simmer baobab leaf powder with dried fish, onion and stock into a soup.','Serve the tuwo with the kuka soup ladled over.'],note:'A Hausa northern staple — mucilaginous baobab-leaf soup over pounded rice, cheap and warming.'},
      'suya-skewers':{id:'suya-skewers',name:'Suya Skewers',cuisine:'Nigerian',tagline:'Dinner · Hausa, grill night',cost:5.0,protein:38,timeMin:20,ingredients:[{item:'Beef steak',qty:'220g'},{item:'Suya spice (yaji)',qty:'2 tbsp'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'1'},{item:'Cabbage',qty:'handful'}],steps:['Thread thin beef strips onto skewers.','Coat generously in suya spice and grill hot and fast.','Serve with sliced onion, tomato and cabbage on the side.'],note:'Hausa street food after dark — smoky, peanut-spiced beef skewers, always eaten standing up.'},
      'eshabwe-kalo':{id:'eshabwe-kalo',name:'Eshabwe & Kalo',cuisine:'Ugandan',tagline:'Lunch · Banyankole',cost:3.2,protein:14,timeMin:25,ingredients:[{item:'Ghee',qty:'3 tbsp'},{item:'Milk',qty:'½ cup'},{item:'Millet flour',qty:'1 cup'},{item:'Onion',qty:'½'}],steps:['Whisk millet flour into boiling water until stiff — that\u2019s kalo.','Warm ghee with milk and a little onion until it emulsifies into a rich sauce — eshabwe.','Serve the kalo with the eshabwe spooned over.'],note:'A Banyankole classic from cattle-keeping country — kalo (millet bread) dipped in rich ghee sauce.'},
      'malakwang':{id:'malakwang',name:'Malakwang (Sour Greens)',cuisine:'Ugandan',tagline:'Lunch · Acholi',cost:2.6,protein:16,timeMin:35,ingredients:[{item:'Malakwang leaves (sour greens)',qty:'2 handfuls'},{item:'Peanut butter',qty:'2 tbsp'},{item:'Onion',qty:'1'},{item:'Simsim (sesame)',qty:'1 tbsp'}],steps:['Simmer the sour greens until tender.','Stir in peanut butter and toasted simsim to thicken.','Serve with posho or sweet potato.'],note:'An Acholi favourite from the north — tangy greens softened into a nutty, simsim-flecked sauce.'},
      'sarson-makki':{id:'sarson-makki',name:'Sarson da Saag & Makki Roti',cuisine:'Indian',tagline:'Dinner · Punjabi winter',cost:3.0,protein:14,timeMin:40,ingredients:[{item:'Mustard greens',qty:'2 handfuls'},{item:'Spinach',qty:'1 handful'},{item:'Corn flour (makki)',qty:'1 cup'},{item:'Ginger',qty:'1 thumb'},{item:'Garlic',qty:'2 cloves'}],steps:['Simmer mustard greens and spinach until soft, then blend coarsely.','Cook down with ginger and garlic until thick.','Pat corn flour into flatbreads and griddle; serve alongside.'],note:'A Punjabi winter classic — slow-cooked mustard greens with warm cornbread, built for cold months.'},
      'sambar-rice':{id:'sambar-rice',name:'Sambar & Rice',cuisine:'Indian',tagline:'Lunch · South Indian, freezer-friendly',cost:2.2,protein:16,timeMin:30,ingredients:[{item:'Red lentils',qty:'½ cup'},{item:'Carrot',qty:'1'},{item:'Onion',qty:'1'},{item:'Tamarind',qty:'1 tbsp'},{item:'Sambar powder',qty:'1 tbsp'},{item:'Rice',qty:'½ cup'}],steps:['Simmer lentils with carrot until soft.','Stir in tamarind and sambar powder; simmer 10 more minutes.','Serve hot over steamed rice.'],note:'A South Indian everyday staple — tangy, spiced lentil stew that freezes and reheats beautifully.'},
      'gujarati-khichdi':{id:'gujarati-khichdi',name:'Gujarati Khichdi',cuisine:'Indian',tagline:'Lunch · Gujarati, quick',cost:1.8,protein:14,timeMin:25,ingredients:[{item:'Rice',qty:'½ cup'},{item:'Red lentils',qty:'½ cup'},{item:'Turmeric',qty:'pinch'},{item:'Cumin',qty:'½ tsp'},{item:'Ghee',qty:'1 tbsp'}],steps:['Rinse rice and lentils together.','Simmer with turmeric until soft and porridge-like.','Finish with a spoon of ghee and toasted cumin.'],note:'Gujarat\u2019s ultimate comfort bowl — soft, simple, and endlessly adaptable.'},
      'bengali-fish-curry':{id:'bengali-fish-curry',name:'Machher Jhol (Bengali Fish Curry)',cuisine:'Indian',tagline:'Dinner · Bengali',cost:5.4,protein:32,timeMin:35,ingredients:[{item:'White fish fillet',qty:'1'},{item:'Potato',qty:'1'},{item:'Turmeric',qty:'pinch'},{item:'Mustard seeds',qty:'½ tsp'},{item:'Tomato',qty:'1'},{item:'Rice',qty:'½ cup'}],steps:['Fry potato and fish lightly until golden.','Simmer with turmeric and tomato until the potato is tender.','Serve over steamed rice.'],note:'Machher Jhol — Bengal\u2019s everyday fish curry, light on spice, big on comfort.'},
      'cacio-e-pepe':{id:'cacio-e-pepe',name:'Cacio e Pepe',cuisine:'Italian',tagline:'Dinner · Roman, budget icon',cost:2.4,protein:16,timeMin:15,ingredients:[{item:'Spaghetti',qty:'80g'},{item:'Pecorino cheese',qty:'40g'},{item:'Black pepper',qty:'1 tsp'}],steps:['Boil the spaghetti, saving a cup of starchy pasta water.','Off heat, toss with grated pecorino and cracked pepper, splashing in pasta water until silky.','Plate immediately, twirled high.'],note:'Rome\u2019s three-ingredient miracle — proof that budget cooking can still be a little glamorous.'},
      'ribollita':{id:'ribollita',name:'Ribollita (Bread & Bean Soup)',cuisine:'Italian',tagline:'Lunch · Tuscan, budget',cost:2.6,protein:14,timeMin:40,ingredients:[{item:'Stale bread',qty:'2 slices'},{item:'Kidney beans',qty:'1 can'},{item:'Carrot',qty:'1'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'}],steps:['Soften onion and carrot, then add tomato and beans with a splash of water.','Simmer into a thick soup, mashing some beans as it cooks.','Tear in stale bread and let it soak and thicken before serving.'],note:'A Tuscan farmhouse trick for using up yesterday\u2019s bread — thick, hearty, and nearly free.'},
      'pasta-alla-norma':{id:'pasta-alla-norma',name:'Pasta alla Norma',cuisine:'Italian',tagline:'Lunch · Sicilian',cost:2.8,protein:12,timeMin:35,ingredients:[{item:'Pasta',qty:'80g'},{item:'Eggplant',qty:'1'},{item:'Tomato',qty:'3'},{item:'Garlic',qty:'1 clove'},{item:'Ricotta',qty:'2 tbsp'}],steps:['Fry cubed eggplant until golden and soft.','Simmer tomato and garlic into a quick sauce, then fold in the eggplant.','Toss with pasta and finish with a spoon of ricotta.'],note:'Sicily\u2019s tribute to fried eggplant — humble vegetables dressed up as a Sunday plate.'},
      'pasta-e-fagioli':{id:'pasta-e-fagioli',name:'Pasta e Fagioli',cuisine:'Italian',tagline:'Lunch · Neapolitan, budget',cost:2.0,protein:16,timeMin:30,ingredients:[{item:'Pasta',qty:'60g'},{item:'Kidney beans',qty:'1 can'},{item:'Tomato',qty:'2'},{item:'Garlic',qty:'1 clove'},{item:'Parmesan',qty:'1 tbsp'}],steps:['Soften garlic, then add tomato and beans with a splash of water.','Simmer 15 minutes, mashing some beans to thicken the broth.','Add the pasta directly to the pot and cook until tender.'],note:'A Neapolitan grandmother\u2019s trick for stretching a few beans into a full meal.'},
      'zanzibar-biryani':{id:'zanzibar-biryani',name:'Zanzibar Biryani',cuisine:'Swahili',tagline:'Dinner · Zanzibari, batch it',cost:5.8,protein:36,timeMin:50,ingredients:[{item:'Rice',qty:'1 cup'},{item:'Chicken thighs',qty:'2'},{item:'Yogurt',qty:'¼ cup'},{item:'Zanzibar biryani masala',qty:'1 tbsp'},{item:'Onion',qty:'1'},{item:'Potato',qty:'1'}],steps:['Marinate chicken in yogurt and biryani masala.','Fry onion until deep golden, then layer with chicken, potato and parboiled rice.','Cover tightly and steam 25 minutes until fragrant.'],note:'Zanzibar\u2019s spice-island take on biryani — saffron-gold rice fragrant with cloves and cardamom.'},
      'urojo-soup':{id:'urojo-soup',name:'Urojo (Zanzibar Mix Soup)',cuisine:'Swahili',tagline:'Lunch · Zanzibari, budget',cost:2.4,protein:14,timeMin:30,ingredients:[{item:'Potato',qty:'2'},{item:'Mango powder',qty:'1 tsp'},{item:'Tamarind',qty:'1 tbsp'},{item:'Chili',qty:'1'},{item:'Cassava crisps',qty:'handful'}],steps:['Boil and mash the potato into the broth to thicken it.','Season with mango powder, tamarind and chili for that signature tang.','Ladle into a bowl and top with cassava crisps.'],note:'Zanzibar\u2019s beloved "urojo" — Mombasa and Zanzibar street food, sour-sweet and endlessly topped.'}
    };

export const mixedPlan = [
      {name:'Mon',date:'Jul 13',breakfast:{id:'greek-yogurt-bowl'},lunch:{id:'githeri'},dinner:{id:'jollof-chicken',batch:2}},
      {name:'Tue',date:'Jul 14',breakfast:{id:'overnight-oats'},lunch:{id:'jollof-chicken',leftover:'Mon'},dinner:{id:'coconut-fish-curry'}},
      {name:'Wed',date:'Jul 15',breakfast:{id:'veggie-omelette'},lunch:{id:'maharagwe-nazi'},dinner:{id:'chicken-tikka',batch:2}},
      {name:'Thu',date:'Jul 16',breakfast:{id:'protein-smoothie'},lunch:{id:'chicken-tikka',leftover:'Wed'},dinner:{id:'matoke-groundnut'}},
      {name:'Fri',date:'Jul 17',breakfast:{id:'cottage-toast'},lunch:{id:'chana-masala',batch:2},dinner:{id:'spaghetti-bolognese'}},
      {name:'Sat',date:'Jul 18',breakfast:{id:'mango-fruit-bowl'},lunch:{id:'chana-masala',leftover:'Fri'},dinner:{id:'nyama-choma'}},
      {name:'Sun',date:'Jul 19',breakfast:{id:'overnight-oats'},lunch:{id:'pilau',batch:2,freezer:1},dinner:{id:'pesto-chicken-pasta'}}
    ];

export const cuisineMains = {
      Kenyan:['githeri','nyama-choma','sukuma-ugali','mukimo-beef','omena-ugali','muthokoi','ingokho-stew'],
      Swahili:['coconut-fish-curry','pilau','mishkaki-skewers','maharagwe-nazi','zanzibar-biryani','urojo-soup'],
      Nigerian:['jollof-chicken','egusi-soup','efo-riro','moi-moi-plantain','amala-ewedu','ofe-nsala','tuwo-kuka','suya-skewers'],
      Ugandan:['matoke-groundnut','luwombo-chicken','beef-posho','doodo-groundnut','eshabwe-kalo','malakwang'],
      Indian:['chicken-tikka','chana-masala','dal-tadka','palak-paneer','sarson-makki','sambar-rice','gujarati-khichdi','bengali-fish-curry'],
      Italian:['spaghetti-bolognese','pesto-chicken-pasta','minestrone-crostini','chicken-parmigiana','cacio-e-pepe','ribollita','pasta-alla-norma','pasta-e-fagioli']
    };

export const cuisineBreakfasts = {
      Kenyan:['mandazi-chai','kenyan-uji','mursik-sweet-potato'],
      Swahili:['vitumbua-chai','bajia-chutney'],
      Nigerian:['akara-pap','yam-egg-sauce'],
      Ugandan:['rolex-wrap','katogo'],
      Indian:['veg-upma','besan-chilla'],
      Italian:['ricotta-toast','uova-pomodoro']
    };

export const neutralBreakfasts = ['greek-yogurt-bowl','mango-fruit-bowl','overnight-oats','veggie-omelette','protein-smoothie','cottage-toast'];

export const currency = {
      Kenyan:{code:'KES',symbol:'KSh ',rate:129,ppp:0.34,dec:0,budgetMin:1750,budgetMax:8000,budgetStep:250,budgetDefault:2500},
      Swahili:{code:'TZS',symbol:'TSh ',rate:2620,ppp:0.34,dec:0,budgetMin:55000,budgetMax:200000,budgetStep:5000,budgetDefault:70000},
      Nigerian:{code:'NGN',symbol:'₦',rate:1380,ppp:0.4,dec:0,budgetMin:32500,budgetMax:90000,budgetStep:2500,budgetDefault:40000},
      Ugandan:{code:'UGX',symbol:'USh ',rate:3690,ppp:0.3,dec:0,budgetMin:70000,budgetMax:280000,budgetStep:10000,budgetDefault:90000},
      Indian:{code:'INR',symbol:'₹',rate:96,ppp:0.32,dec:0,budgetMin:1400,budgetMax:5000,budgetStep:100,budgetDefault:2000},
      Italian:{code:'EUR',symbol:'€',rate:0.88,ppp:0.9,dec:2,budgetMin:40,budgetMax:80,budgetStep:2.5,budgetDefault:50}
    };

export const catOf = {
      'Greek yogurt':'Dairy & Eggs','Milk':'Dairy & Eggs','Feta':'Dairy & Eggs','Cottage cheese':'Dairy & Eggs','Parmesan':'Dairy & Eggs','Eggs':'Dairy & Eggs','Yogurt':'Dairy & Eggs','Paneer':'Dairy & Eggs','Mozzarella':'Dairy & Eggs','Ricotta':'Dairy & Eggs','Mursik (fermented milk)':'Dairy & Eggs','Pecorino cheese':'Dairy & Eggs',
      'Blueberries':'Produce','Banana':'Produce','Mango':'Produce','Spinach':'Produce','Cherry tomatoes':'Produce','Bell pepper':'Produce','Carrot':'Produce','Red onion':'Produce','Lime':'Produce','Lemon':'Produce','Onion':'Produce','Tomato':'Produce','Cilantro':'Produce','Chili':'Produce','Ginger':'Produce','Garlic':'Produce','Green banana (matoke)':'Produce','Collard greens':'Produce','Potato':'Produce','Green peas':'Produce','Corn kernels':'Produce','Plantain':'Produce','Yam':'Produce','Amaranth greens (doodo)':'Produce','Cabbage':'Produce','Sweet potato':'Produce','Jute leaves (ewedu)':'Produce','Malakwang leaves (sour greens)':'Produce','Mustard greens':'Produce','Eggplant':'Produce',
      'Chicken breast':'Protein','Chicken thighs':'Protein','White fish fillet':'Protein','Beef steak':'Protein','Ground beef':'Protein','Beef stew meat':'Protein','Omena (dried silverfish)':'Protein','Chicken (indigenous)':'Protein','Dried fish':'Protein',
      'Rolled oats':'Grains & Bread','Rice':'Grains & Bread','Sourdough bread':'Grains & Bread','Pasta':'Grains & Bread','Spaghetti':'Grains & Bread','Flour':'Grains & Bread','Millet flour':'Grains & Bread','Rice flour':'Grains & Bread','Cornmeal (ugali)':'Grains & Bread','Cornmeal (posho)':'Grains & Bread','Cornmeal (pap)':'Grains & Bread','Chapati':'Grains & Bread','Roti':'Grains & Bread','Semolina':'Grains & Bread','Yam flour (amala)':'Grains & Bread','Corn flour (makki)':'Grains & Bread','Stale bread':'Grains & Bread',
      'Honey':'Pantry','Almonds':'Pantry','Chia seeds':'Pantry','Peanut butter':'Pantry','Olive oil':'Pantry','Chickpeas (canned)':'Pantry','Kidney beans':'Pantry','Maize (canned)':'Pantry','Cumin':'Pantry','Pesto':'Pantry','Whey protein':'Pantry','Tomato paste':'Pantry','Coconut milk':'Pantry','Garam masala':'Pantry','Pilau masala':'Pantry','Palm oil':'Pantry','Ground egusi (melon seeds)':'Pantry','Stock cube':'Pantry','Sugar':'Pantry','Cardamom':'Pantry','Tea leaves':'Pantry','Cinnamon':'Pantry','Yeast':'Pantry','Chickpea flour':'Pantry','Turmeric':'Pantry','Tamarind':'Pantry','Black-eyed peas':'Pantry','Red lentils':'Pantry','Mustard seeds':'Pantry','Breadcrumbs':'Pantry','Walnuts':'Pantry','Dehulled maize (muthokoi)':'Pantry','Pigeon peas':'Pantry','Locust beans':'Pantry','Ground crayfish':'Pantry','Baobab leaf powder (kuka)':'Pantry','Suya spice (yaji)':'Pantry','Ghee':'Pantry','Simsim (sesame)':'Pantry','Sambar powder':'Pantry','Zanzibar biryani masala':'Pantry','Mango powder':'Pantry','Cassava crisps':'Pantry','Black pepper':'Pantry'
    };

// Emoji stand-ins for recipe photography — zero network cost, render natively,
// and read instantly at thumbnail size on small screens.
export const emojiOf = {
  'greek-yogurt-bowl':'🫐','mango-fruit-bowl':'🥭','overnight-oats':'🥣','veggie-omelette':'🍳',
  'protein-smoothie':'🥤','cottage-toast':'🍞','githeri':'🌽','nyama-choma':'🥩',
  'jollof-chicken':'🍗','egusi-soup':'🍲','coconut-fish-curry':'🐟','pilau':'🍚',
  'chicken-tikka':'🍛','chana-masala':'🥘','matoke-groundnut':'🍌','luwombo-chicken':'🍗',
  'spaghetti-bolognese':'🍝','pesto-chicken-pasta':'🌿','sukuma-ugali':'🥬','mukimo-beef':'🥔',
  'mandazi-chai':'🍩','kenyan-uji':'🥣','mishkaki-skewers':'🍢','maharagwe-nazi':'🥥',
  'vitumbua-chai':'🥞','bajia-chutney':'🧆','efo-riro':'🥬','moi-moi-plantain':'🍌',
  'akara-pap':'🧆','yam-egg-sauce':'🍠','beef-posho':'🍲','doodo-groundnut':'🥜',
  'rolex-wrap':'🌯','katogo':'🍲','dal-tadka':'🍛','palak-paneer':'🧀',
  'veg-upma':'🍚','besan-chilla':'🥞','minestrone-crostini':'🍅','chicken-parmigiana':'🧀',
  'ricotta-toast':'🍯','uova-pomodoro':'🍅','omena-ugali':'🐟','muthokoi':'🌽',
  'ingokho-stew':'🍗','mursik-sweet-potato':'🥛','amala-ewedu':'🥣','ofe-nsala':'🐟',
  'tuwo-kuka':'🍚','suya-skewers':'🍢','eshabwe-kalo':'🧈','malakwang':'🌿',
  'sarson-makki':'🥬','sambar-rice':'🍛','gujarati-khichdi':'🍚','bengali-fish-curry':'🐟',
  'cacio-e-pepe':'🍝','ribollita':'🍞','pasta-alla-norma':'🍆','pasta-e-fagioli':'🍝',
  'zanzibar-biryani':'🍛','urojo-soup':'🍜'
};

// Pantry suggestion pool (from the design's renderVals).
export const pantryPool = ['Almonds','Peanut butter','Milk','Onion','Lemon','Parmesan','Chickpeas (canned)','Kidney beans','Coconut milk','Ginger','Garlic','Tomato paste','Pilau masala','Black-eyed peas','Red lentils','Chickpea flour','Turmeric','Tamarind','Semolina','Breadcrumbs','Cinnamon','Ghee','Suya spice (yaji)','Sambar powder','Locust beans','Simsim (sesame)','Ground crayfish'];

export const CATEGORY_ORDER = ['Produce','Protein','Dairy & Eggs','Grains & Bread','Pantry'];
export const SLOTS = ['breakfast','lunch','dinner'];

// ---- Expanded library (more variety, breakfast-heavy) ----
// Appended as a merge so the 1:1 design data above stays untouched.
Object.assign(recipes, {
  'chia-pudding':{id:'chia-pudding',name:'Vanilla Chia Pudding',cuisine:'',tagline:'Breakfast · make-ahead',cost:2.2,protein:18,timeMin:5,ingredients:[{item:'Chia seeds',qty:'3 tbsp'},{item:'Milk',qty:'1 cup'},{item:'Honey',qty:'1 tsp'},{item:'Banana',qty:'½'},{item:'Blueberries',qty:'¼ cup'}],steps:['Whisk chia into the milk with honey.','Chill overnight until set and spoonable.','Top with banana and berries.'],note:'Stir once before bed and breakfast makes itself.'},
  'avocado-toast':{id:'avocado-toast',name:'Avocado & Egg Toast',cuisine:'',tagline:'Breakfast · 8 min',cost:2.8,protein:20,timeMin:8,ingredients:[{item:'Sourdough bread',qty:'1 slice'},{item:'Avocado',qty:'½'},{item:'Eggs',qty:'1'},{item:'Cherry tomatoes',qty:'4'},{item:'Chili',qty:'pinch'}],steps:['Toast the sourdough and mash the avocado on top.','Fry or poach the egg and slide it over.','Scatter tomato and a pinch of chili.'],note:'Creamy, savoury and on the plate in under ten minutes.'},
  'banana-pancakes':{id:'banana-pancakes',name:'Banana Oat Pancakes',cuisine:'',tagline:'Breakfast · 15 min',cost:2.0,protein:16,timeMin:15,ingredients:[{item:'Rolled oats',qty:'½ cup'},{item:'Eggs',qty:'2'},{item:'Banana',qty:'1'},{item:'Milk',qty:'¼ cup'},{item:'Honey',qty:'1 tsp'}],steps:['Blend oats, eggs, banana and milk into a batter.','Cook small pancakes on a hot pan until golden.','Stack and drizzle with honey.'],note:'Flourless and naturally sweet — a weekend feel on a weekday.'},
  'shakshuka':{id:'shakshuka',name:'Shakshuka',cuisine:'',tagline:'Breakfast · 18 min',cost:2.6,protein:22,timeMin:18,ingredients:[{item:'Eggs',qty:'2'},{item:'Tomato',qty:'3'},{item:'Bell pepper',qty:'1'},{item:'Onion',qty:'½'},{item:'Cumin',qty:'1 tsp'}],steps:['Soften onion and pepper, add tomato and cumin.','Simmer into a thick sauce.','Crack in the eggs and cover until just set.'],note:'Eggs poached in a spiced tomato sauce — mop up with bread.'},
  'berry-parfait':{id:'berry-parfait',name:'Berry Granola Parfait',cuisine:'',tagline:'Breakfast · no cook',cost:2.9,protein:24,timeMin:5,ingredients:[{item:'Greek yogurt',qty:'1 cup'},{item:'Granola',qty:'⅓ cup'},{item:'Blueberries',qty:'½ cup'},{item:'Honey',qty:'1 tsp'},{item:'Almonds',qty:'handful'}],steps:['Layer yogurt, granola and berries in a glass.','Repeat the layers.','Finish with honey and almonds.'],note:'Crunch, cream and 24g protein — no stove required.'},
  'nduma-eggs':{id:'nduma-eggs',name:'Nduma (Arrowroot) & Eggs',cuisine:'Kenyan',tagline:'Breakfast · hearty',cost:2.2,protein:18,timeMin:20,ingredients:[{item:'Arrowroot (nduma)',qty:'250g'},{item:'Eggs',qty:'2'},{item:'Tomato',qty:'1'},{item:'Onion',qty:'½'}],steps:['Boil the arrowroot until tender.','Scramble eggs with tomato and onion.','Serve the eggs over sliced nduma.'],note:'A filling upcountry breakfast — earthy arrowroot against soft eggs.'},
  'kenyan-sweet-potato-eggs':{id:'kenyan-sweet-potato-eggs',name:'Sweet Potato & Boiled Eggs',cuisine:'Kenyan',tagline:'Breakfast · simple',cost:2.0,protein:16,timeMin:18,ingredients:[{item:'Sweet potato',qty:'1'},{item:'Eggs',qty:'2'},{item:'Spinach',qty:'1 handful'},{item:'Tomato',qty:'1'}],steps:['Boil the sweet potato and eggs together.','Wilt spinach with a little tomato.','Plate the potato, eggs and greens.'],note:'The classic tea-time plate, sized up into a proper breakfast.'},
  'mahamri-mbaazi':{id:'mahamri-mbaazi',name:'Mahamri & Mbaazi',cuisine:'Swahili',tagline:'Breakfast · coastal',cost:2.4,protein:16,timeMin:30,ingredients:[{item:'Flour',qty:'1 cup'},{item:'Coconut milk',qty:'½ cup'},{item:'Cardamom',qty:'pinch'},{item:'Pigeon peas',qty:'¾ cup'},{item:'Sugar',qty:'1 tbsp'}],steps:['Make a cardamom-coconut dough, rest and fry into mahamri.','Simmer pigeon peas in coconut milk until creamy.','Serve the mbaazi alongside the fried mahamri.'],note:'Zanzibar mornings — cardamom doughnuts dipped in coconut peas.'},
  'viazi-karai':{id:'viazi-karai',name:'Viazi Karai',cuisine:'Swahili',tagline:'Breakfast · fried & spiced',cost:2.0,protein:9,timeMin:22,ingredients:[{item:'Potato',qty:'3'},{item:'Chickpea flour',qty:'½ cup'},{item:'Turmeric',qty:'pinch'},{item:'Chili',qty:'1'}],steps:['Parboil the potatoes.','Dip in a turmeric chickpea batter.','Fry until golden and serve with chili.'],note:'Mombasa street food — turmeric-gold potato fritters.'},
  'plantain-frittata':{id:'plantain-frittata',name:'Plantain Frittata',cuisine:'Nigerian',tagline:'Breakfast · 15 min',cost:2.4,protein:20,timeMin:15,ingredients:[{item:'Plantain',qty:'1'},{item:'Eggs',qty:'3'},{item:'Bell pepper',qty:'½'},{item:'Onion',qty:'½'},{item:'Tomato',qty:'1'}],steps:['Fry plantain slices until caramelised.','Pour whisked eggs with pepper, onion and tomato over.','Cook low until set, then slice like a frittata.'],note:'Sweet plantain baked into savoury eggs — a Lagos twist.'},
  'nigerian-fried-yam-eggs':{id:'nigerian-fried-yam-eggs',name:'Fried Yam & Egg Sauce',cuisine:'Nigerian',tagline:'Breakfast · hearty',cost:2.6,protein:18,timeMin:22,ingredients:[{item:'Yam',qty:'300g'},{item:'Eggs',qty:'2'},{item:'Tomato',qty:'2'},{item:'Onion',qty:'½'},{item:'Chili',qty:'1'}],steps:['Fry yam batons until crisp and golden.','Make a peppery egg sauce with tomato, onion and chili.','Serve the sauce spooned over the fried yam.'],note:'Crisp yam against a spicy egg sauce — a Nigerian favourite.'},
  'kabalagala':{id:'kabalagala',name:'Kabalagala (Plantain Pancakes)',cuisine:'Ugandan',tagline:'Breakfast · pancakes',cost:1.8,protein:10,timeMin:20,ingredients:[{item:'Plantain',qty:'2'},{item:'Flour',qty:'½ cup'},{item:'Simsim (sesame)',qty:'2 tbsp'},{item:'Sugar',qty:'1 tbsp'}],steps:['Mash ripe plantain and mix with flour and sesame.','Shape into small rounds.','Fry until golden on both sides.'],note:'Uganda’s sweet plantain pancakes, nutty with simsim.'},
  'ugandan-millet-porridge':{id:'ugandan-millet-porridge',name:'Millet Porridge (Bushera)',cuisine:'Ugandan',tagline:'Breakfast · warm',cost:1.4,protein:12,timeMin:15,ingredients:[{item:'Millet flour',qty:'½ cup'},{item:'Milk',qty:'1 cup'},{item:'Simsim (sesame)',qty:'1 tbsp'},{item:'Sugar',qty:'1 tbsp'}],steps:['Whisk millet flour with cold water until smooth.','Simmer, stirring, until thick.','Loosen with milk, sweeten and top with simsim.'],note:'A warm, fermented-grain porridge to start a Ugandan morning.'},
  'masala-omelette':{id:'masala-omelette',name:'Masala Omelette',cuisine:'Indian',tagline:'Breakfast · 10 min',cost:2.0,protein:22,timeMin:10,ingredients:[{item:'Eggs',qty:'3'},{item:'Onion',qty:'½'},{item:'Tomato',qty:'1'},{item:'Chili',qty:'1'},{item:'Cilantro',qty:'handful'}],steps:['Whisk eggs with onion, tomato, chili and cilantro.','Pour into a hot pan.','Fold and slide out when just set.'],note:'The spiced omelette every Indian kitchen makes before work.'},
  'poha':{id:'poha',name:'Vegetable Poha',cuisine:'Indian',tagline:'Breakfast · light',cost:1.6,protein:10,timeMin:15,ingredients:[{item:'Poha (flattened rice)',qty:'1 cup'},{item:'Onion',qty:'½'},{item:'Potato',qty:'1'},{item:'Turmeric',qty:'pinch'},{item:'Mustard seeds',qty:'½ tsp'}],steps:['Rinse the poha until just soft.','Fry mustard seeds, onion and potato with turmeric.','Fold the poha through and warm.'],note:'Feather-light flattened rice — a Maharashtrian morning staple.'},
  'italian-frittata':{id:'italian-frittata',name:'Potato & Parmesan Frittata',cuisine:'Italian',tagline:'Breakfast · 18 min',cost:2.6,protein:22,timeMin:18,ingredients:[{item:'Eggs',qty:'3'},{item:'Potato',qty:'1'},{item:'Parmesan',qty:'2 tbsp'},{item:'Spinach',qty:'1 handful'},{item:'Onion',qty:'½'}],steps:['Fry sliced potato and onion until soft.','Add spinach, pour over whisked eggs and parmesan.','Cook low until set, then slice.'],note:'A frittata turns leftover potato into a proper plate.'},
  'yogurt-granola':{id:'yogurt-granola',name:'Yogurt, Honey & Granola',cuisine:'Italian',tagline:'Breakfast · no cook',cost:2.4,protein:18,timeMin:5,ingredients:[{item:'Yogurt',qty:'1 cup'},{item:'Granola',qty:'⅓ cup'},{item:'Honey',qty:'1 tsp'},{item:'Walnuts',qty:'handful'},{item:'Blueberries',qty:'¼ cup'}],steps:['Spoon yogurt into a bowl.','Scatter granola, walnuts and berries.','Drizzle with honey.'],note:'The Italian colazione — light, sweet and quick.'},
  'kenyan-wet-fry-beef':{id:'kenyan-wet-fry-beef',name:'Beef Wet Fry & Ugali',cuisine:'Kenyan',tagline:'Dinner · everyday',cost:5.0,protein:36,timeMin:30,ingredients:[{item:'Beef stew meat',qty:'200g'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Bell pepper',qty:'1'},{item:'Cornmeal (ugali)',qty:'1 cup'}],steps:['Brown the beef, then add onion, tomato and pepper.','Simmer into a thick wet fry.','Cook ugali stiff and serve alongside.'],note:'Kenya’s go-to dinner — beef wet fry against a mound of ugali.'},
  'kuku-wa-kupaka':{id:'kuku-wa-kupaka',name:'Kuku wa Kupaka',cuisine:'Swahili',tagline:'Dinner · coconut grilled chicken',cost:6.0,protein:40,timeMin:35,ingredients:[{item:'Chicken thighs',qty:'2'},{item:'Coconut milk',qty:'½ can'},{item:'Lime',qty:'1'},{item:'Garlic',qty:'2 cloves'},{item:'Chili',qty:'1'}],steps:['Grill or sear the chicken until charred.','Simmer coconut milk with garlic, lime and chili.','Coat the chicken in the sauce and warm through.'],note:'Coastal grilled chicken bathed in a tangy coconut sauce.'},
  'ofada-stew':{id:'ofada-stew',name:'Ofada Rice & Ayamase',cuisine:'Nigerian',tagline:'Dinner · rich & spicy',cost:5.4,protein:32,timeMin:40,ingredients:[{item:'Rice',qty:'1 cup'},{item:'Beef stew meat',qty:'180g'},{item:'Bell pepper',qty:'2'},{item:'Palm oil',qty:'2 tbsp'},{item:'Onion',qty:'1'}],steps:['Blend green peppers and fry down in palm oil.','Add beef and simmer into a deep, spicy stew.','Serve over ofada-style rice.'],note:'A smoky green-pepper stew — Nigerian special-occasion food.'},
  'ugandan-groundnut-chicken':{id:'ugandan-groundnut-chicken',name:'Groundnut Chicken Stew',cuisine:'Ugandan',tagline:'Dinner · nutty & rich',cost:5.2,protein:38,timeMin:40,ingredients:[{item:'Chicken thighs',qty:'2'},{item:'Peanut butter',qty:'2 tbsp'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Bell pepper',qty:'1'}],steps:['Brown the chicken with onion, tomato and pepper.','Loosen peanut butter with stock and stir in.','Simmer until the sauce is thick and silky.'],note:'Chicken in a rich groundnut sauce — deeply comforting.'},
  'rajma-rice':{id:'rajma-rice',name:'Rajma Chawal',cuisine:'Indian',tagline:'Lunch · freezer-friendly',cost:2.6,protein:20,timeMin:30,ingredients:[{item:'Kidney beans',qty:'1 can'},{item:'Tomato',qty:'2'},{item:'Onion',qty:'1'},{item:'Garam masala',qty:'1 tbsp'},{item:'Rice',qty:'½ cup'}],steps:['Fry onion and tomato into a masala base.','Add kidney beans and simmer until thick.','Serve over steamed rice.'],note:'North India’s Sunday comfort bowl — beans and rice, and it freezes well.'},
  'tuna-white-bean-salad':{id:'tuna-white-bean-salad',name:'Tuna & White Bean Salad',cuisine:'Italian',tagline:'Lunch · no cook',cost:3.4,protein:26,timeMin:10,ingredients:[{item:'Canned tuna',qty:'1 can'},{item:'Kidney beans',qty:'1 can'},{item:'Red onion',qty:'½'},{item:'Lemon',qty:'½'},{item:'Cilantro',qty:'handful'}],steps:['Drain and flake the tuna over the beans.','Add thin red onion and torn herbs.','Dress with lemon and olive oil.'],note:'A ten-minute Tuscan-style lunch — no stove, 26g protein.'},
});

Object.assign(emojiOf, {
  'chia-pudding':'🍮','avocado-toast':'🥑','banana-pancakes':'🥞','shakshuka':'🍳','berry-parfait':'🍨',
  'nduma-eggs':'🍠','kenyan-sweet-potato-eggs':'🥚','mahamri-mbaazi':'🍩','viazi-karai':'🥔',
  'plantain-frittata':'🍳','nigerian-fried-yam-eggs':'🍠','kabalagala':'🥞','ugandan-millet-porridge':'🥣',
  'masala-omelette':'🍳','poha':'🍚','italian-frittata':'🍳','yogurt-granola':'🍯',
  'kenyan-wet-fry-beef':'🥩','kuku-wa-kupaka':'🍗','ofada-stew':'🍚','ugandan-groundnut-chicken':'🍗',
  'rajma-rice':'🍛','tuna-white-bean-salad':'🥗',
});

Object.assign(catOf, {
  'Avocado':'Produce','Granola':'Grains & Bread','Arrowroot (nduma)':'Produce',
  'Poha (flattened rice)':'Grains & Bread','Canned tuna':'Protein',
});

// Wire new breakfasts/mains into the generator pools.
neutralBreakfasts.push('chia-pudding','avocado-toast','banana-pancakes','shakshuka','berry-parfait');
cuisineBreakfasts.Kenyan.push('nduma-eggs','kenyan-sweet-potato-eggs');
cuisineBreakfasts.Swahili.push('mahamri-mbaazi','viazi-karai');
cuisineBreakfasts.Nigerian.push('plantain-frittata','nigerian-fried-yam-eggs');
cuisineBreakfasts.Ugandan.push('kabalagala','ugandan-millet-porridge');
cuisineBreakfasts.Indian.push('masala-omelette','poha');
cuisineBreakfasts.Italian.push('italian-frittata','yogurt-granola');
cuisineMains.Kenyan.push('kenyan-wet-fry-beef');
cuisineMains.Swahili.push('kuku-wa-kupaka');
cuisineMains.Nigerian.push('ofada-stew');
cuisineMains.Ugandan.push('ugandan-groundnut-chicken');
cuisineMains.Indian.push('rajma-rice');
cuisineMains.Italian.push('tuna-white-bean-salad');

// Curated, dish-matched photos (Wikipedia/Wikimedia, freely licensed).
export const photoMap = {
  'akara-pap':'https://upload.wikimedia.org/wikipedia/commons/b/bb/Beans_Ball-Akara.jpg',
  'amala-ewedu':'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Amala_with_Ewedu.jpg/960px-Amala_with_Ewedu.jpg',
  'avocado-toast':'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Avocado_toast_at_Voyager_Espresso_%2833134505776%29.jpg/960px-Avocado_toast_at_Voyager_Espresso_%2833134505776%29.jpg',
  'bajia-chutney':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Stuffed_mirchi_bajji_%2816164286908%29.jpg/960px-Stuffed_mirchi_bajji_%2816164286908%29.jpg',
  'banana-pancakes':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg/960px-Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg',
  'beef-posho':'https://upload.wikimedia.org/wikipedia/commons/4/48/Ugali_%26_Sukuma_Wiki.jpg',
  'bengali-fish-curry':'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Alu_ar_dhonepata_diye_Boyal_machher_jhol.jpg/960px-Alu_ar_dhonepata_diye_Boyal_machher_jhol.jpg',
  'berry-parfait':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Parfait_samples_by_pinguino_in_Osaka%2C_Japan.jpg/960px-Parfait_samples_by_pinguino_in_Osaka%2C_Japan.jpg',
  'cacio-e-pepe':'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cacio_e_pepe.jpg/960px-Cacio_e_pepe.jpg',
  'chana-masala':'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Chana_masala.jpg/960px-Chana_masala.jpg',
  'chicken-parmigiana':'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Chicken_parm_at_a_diner.jpg/960px-Chicken_parm_at_a_diner.jpg',
  'chicken-tikka':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Chicken_tikka_masala_%28cropped%29.jpg/960px-Chicken_tikka_masala_%28cropped%29.jpg',
  'coconut-fish-curry':'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Fisheadcurry.JPG/960px-Fisheadcurry.JPG',
  'cottage-toast':'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Cottagecheese200px.jpg/960px-Cottagecheese200px.jpg',
  'dal-tadka':'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/3_types_of_lentil.png/960px-3_types_of_lentil.png',
  'efo-riro':'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Efo_Riro_with_fried_mackerel_fishes_and_roasted_cowskin.jpg/960px-Efo_Riro_with_fried_mackerel_fishes_and_roasted_cowskin.jpg',
  'egusi-soup':'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/EGUSI.JPG/960px-EGUSI.JPG',
  'githeri':'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Githeri_Meal.jpg/960px-Githeri_Meal.jpg',
  'greek-yogurt-bowl':'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/960px-Joghurt.jpg',
  'gujarati-khichdi':'https://upload.wikimedia.org/wikipedia/commons/6/63/Dall_Khichdi.jpg',
  'ingokho-stew':'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Chicken_Noodle_Soup.jpg/960px-Chicken_Noodle_Soup.jpg',
  'italian-frittata':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Frittata02.jpg/960px-Frittata02.jpg',
  'jollof-chicken':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jollof_Rice_with_Stew.jpg/960px-Jollof_Rice_with_Stew.jpg',
  'kabalagala':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kabalagala_slum.jpg/960px-Kabalagala_slum.jpg',
  'katogo':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Matooke_to_the_market.jpg/960px-Matooke_to_the_market.jpg',
  'kenyan-uji':'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Byodoin_Phoenix_Hall_Uji_2009.jpg/960px-Byodoin_Phoenix_Hall_Uji_2009.jpg',
  'kenyan-wet-fry-beef':'https://upload.wikimedia.org/wikipedia/commons/4/48/Ugali_%26_Sukuma_Wiki.jpg',
  'luwombo-chicken':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Chicken_Luwombo.JPG/960px-Chicken_Luwombo.JPG',
  'mahamri-mbaazi':'https://upload.wikimedia.org/wikipedia/commons/6/69/Bowl_of_mandazi.jpg',
  'maharagwe-nazi':'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/2_Chapati_warm_and_ready_to_be_eaten.jpg/960px-2_Chapati_warm_and_ready_to_be_eaten.jpg',
  'mandazi-chai':'https://upload.wikimedia.org/wikipedia/commons/6/69/Bowl_of_mandazi.jpg',
  'mango-fruit-bowl':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Fruktsallad_%28Fruit_salad%29.jpg/960px-Fruktsallad_%28Fruit_salad%29.jpg',
  'masala-omelette':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg/960px-Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg',
  'matoke-groundnut':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Matooke_to_the_market.jpg/960px-Matooke_to_the_market.jpg',
  'minestrone-crostini':'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Minestrone_soup_%285%29.jpg/960px-Minestrone_soup_%285%29.jpg',
  'mishkaki-skewers':'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/%C5%9Ei%C5%9F_kebap_and_pilav.jpg/960px-%C5%9Ei%C5%9F_kebap_and_pilav.jpg',
  'moi-moi-plantain':'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Moin-Moin-good.jpg/960px-Moin-Moin-good.jpg',
  'mukimo-beef':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Mukimo_%26_Beef_Stew.jpg/960px-Mukimo_%26_Beef_Stew.jpg',
  'mursik-sweet-potato':'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Kipsigis_Gourd.jpg/960px-Kipsigis_Gourd.jpg',
  'muthokoi':'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Githeri_Meal.jpg/960px-Githeri_Meal.jpg',
  'nyama-choma':'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Goat_meat_being_roasted.jpg/960px-Goat_meat_being_roasted.jpg',
  'ofada-stew':'https://upload.wikimedia.org/wikipedia/commons/7/7c/Ofada_rise_with_fried_plantain_and_beaf.jpg',
  'ofe-nsala':'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Nsala_Soup_%28Pepper_soup%29.jpg/960px-Nsala_Soup_%28Pepper_soup%29.jpg',
  'omena-ugali':'https://upload.wikimedia.org/wikipedia/commons/4/48/Ugali_%26_Sukuma_Wiki.jpg',
  'overnight-oats':'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Dorset_Cereals_muesli.jpg/960px-Dorset_Cereals_muesli.jpg',
  'palak-paneer':'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Palakpaneer_Rayagada_Odisha_0009.jpg/960px-Palakpaneer_Rayagada_Odisha_0009.jpg',
  'pasta-alla-norma':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Pasta_alla_Norma_-_Wiki_Loves_Sicilia.jpg/960px-Pasta_alla_Norma_-_Wiki_Loves_Sicilia.jpg',
  'pasta-e-fagioli':'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Pasta_e_fagioli_cannellini.jpg/960px-Pasta_e_fagioli_cannellini.jpg',
  'pesto-chicken-pasta':'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/BasilPesto.JPG/960px-BasilPesto.JPG',
  'pilau':'https://upload.wikimedia.org/wikipedia/commons/d/dd/Afghan_Palo.jpg',
  'plantain-frittata':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Frittata02.jpg/960px-Frittata02.jpg',
  'poha':'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Poha.jpg/960px-Poha.jpg',
  'protein-smoothie':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Kiwi_Smoothie.jpg/960px-Kiwi_Smoothie.jpg',
  'rajma-rice':'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Rajma_Masala_%2832081557778%29.jpg/960px-Rajma_Masala_%2832081557778%29.jpg',
  'ribollita':'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Ribollita_Siena.jpg/960px-Ribollita_Siena.jpg',
  'ricotta-toast':'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Ricotte_fresche.jpg/960px-Ricotte_fresche.jpg',
  'sambar-rice':'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Pumpkin_sambar.JPG/960px-Pumpkin_sambar.JPG',
  'sarson-makki':'https://upload.wikimedia.org/wikipedia/commons/c/c8/Saagroti.jpg',
  'shakshuka':'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Shakshuka_by_Calliopejen1.jpg/960px-Shakshuka_by_Calliopejen1.jpg',
  'spaghetti-bolognese':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Tagliatelle_al_rag%C3%B9_%28image_modified%29.jpg/960px-Tagliatelle_al_rag%C3%B9_%28image_modified%29.jpg',
  'sukuma-ugali':'https://upload.wikimedia.org/wikipedia/commons/4/48/Ugali_%26_Sukuma_Wiki.jpg',
  'suya-skewers':'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/SuyavarietiesTX.JPG/960px-SuyavarietiesTX.JPG',
  'tuna-white-bean-salad':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Tuna_fish_sandwiches_for_the_National_School_Lunch_Program_%281%29.jpg/960px-Tuna_fish_sandwiches_for_the_National_School_Lunch_Program_%281%29.jpg',
  'tuwo-kuka':'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Tuwo_Shinkafa_with_garden_egg_Soup.jpg/960px-Tuwo_Shinkafa_with_garden_egg_Soup.jpg',
  'uova-pomodoro':'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Shakshuka_by_Calliopejen1.jpg/960px-Shakshuka_by_Calliopejen1.jpg',
  'veg-upma':'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/A_photo_of_Upma.jpg/960px-A_photo_of_Upma.jpg',
  'veggie-omelette':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg/960px-Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg',
  'viazi-karai':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Stuffed_mirchi_bajji_%2816164286908%29.jpg/960px-Stuffed_mirchi_bajji_%2816164286908%29.jpg',
  'vitumbua-chai':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg/960px-HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg',
  'yogurt-granola':'https://upload.wikimedia.org/wikipedia/commons/9/94/Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg',
  'zanzibar-biryani':'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%22Hyderabadi_Dum_Biryani%22.jpg/960px-%22Hyderabadi_Dum_Biryani%22.jpg',
};

// Curated Commons photos for the remaining dishes (no keyword fallback).
Object.assign(photoMap, {
  'besan-chilla':'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Besan_chilla.jpg/960px-Besan_chilla.jpg',
  'chia-pudding':'https://upload.wikimedia.org/wikipedia/commons/9/90/Chia_seed_pudding_in_a_tea_cup.jpg',
  'doodo-groundnut':'https://upload.wikimedia.org/wikipedia/commons/2/28/African_ugali_sukuma_and_potatoes.jpg',
  'eshabwe-kalo':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kalo_%28African_Millet_Bread%29_1.jpg/960px-Kalo_%28African_Millet_Bread%29_1.jpg',
  'kenyan-sweet-potato-eggs':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Boiled_pumpkin_with_roasted_sweet_potato_and_vegetables.jpg/960px-Boiled_pumpkin_with_roasted_sweet_potato_and_vegetables.jpg',
  'kuku-wa-kupaka':'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Chicken_Coconut_Curry.jpg/960px-Chicken_Coconut_Curry.jpg',
  'malakwang':'https://upload.wikimedia.org/wikipedia/commons/b/b8/Malakwang_dish.jpg',
  'nduma-eggs':'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Arrowroot_%28Maranta_arundinacea%29_Boiled.jpg/960px-Arrowroot_%28Maranta_arundinacea%29_Boiled.jpg',
  'nigerian-fried-yam-eggs':'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Fried_Yam_with_egg_and_Stew.jpg/960px-Fried_Yam_with_egg_and_Stew.jpg',
  'rolex-wrap':'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rolex_%28food%29_01.jpg/960px-Rolex_%28food%29_01.jpg',
  'ugandan-groundnut-chicken':'https://upload.wikimedia.org/wikipedia/commons/0/01/Groundnut_Stew%28_Abom_%29.jpg',
  'ugandan-millet-porridge':'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Millet_porridge.png/960px-Millet_porridge.png',
  'urojo-soup':'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Urojo_Zanzibar_112018.jpg/960px-Urojo_Zanzibar_112018.jpg',
  'yam-egg-sauce':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Boiled_yam_and_egg_sauce.jpg/960px-Boiled_yam_and_egg_sauce.jpg',
});

// ---- Tribe/region labels + chapati dishes (user request) ----
const REGION = {
  githeri:'Kikuyu','nyama-choma':'Nationwide','sukuma-ugali':'Nationwide','mukimo-beef':'Kikuyu',
  'mandazi-chai':'Nationwide','kenyan-uji':'Nationwide','omena-ugali':'Luo',muthokoi:'Kamba',
  'ingokho-stew':'Luhya','mursik-sweet-potato':'Kalenjin','nduma-eggs':'Kikuyu',
  'kenyan-sweet-potato-eggs':'Nationwide','kenyan-wet-fry-beef':'Nationwide',
  'jollof-chicken':'Nationwide','egusi-soup':'Igbo','efo-riro':'Yoruba','moi-moi-plantain':'Nationwide',
  'akara-pap':'Nationwide','yam-egg-sauce':'Nationwide','nigerian-fried-yam-eggs':'Nationwide',
  'plantain-frittata':'Nationwide','amala-ewedu':'Yoruba','ofe-nsala':'Igbo','tuwo-kuka':'Hausa',
  'suya-skewers':'Hausa','ofada-stew':'Yoruba',
  'matoke-groundnut':'Nationwide','luwombo-chicken':'Buganda','beef-posho':'Nationwide',
  'doodo-groundnut':'Nationwide','rolex-wrap':'Nationwide',katogo:'Buganda','eshabwe-kalo':'Banyankole',
  malakwang:'Acholi',kabalagala:'Buganda','ugandan-millet-porridge':'Nationwide','ugandan-groundnut-chicken':'Nationwide',
  'chicken-tikka':'Punjabi','chana-masala':'Punjabi','dal-tadka':'Nationwide','palak-paneer':'Punjabi',
  'veg-upma':'South Indian','besan-chilla':'Nationwide','sarson-makki':'Punjabi','sambar-rice':'South Indian',
  'gujarati-khichdi':'Gujarati','bengali-fish-curry':'Bengali','masala-omelette':'Nationwide',poha:'Maharashtrian','rajma-rice':'Punjabi',
  'spaghetti-bolognese':'Emilian','pesto-chicken-pasta':'Ligurian','minestrone-crostini':'Nationwide',
  'chicken-parmigiana':'Nationwide','ricotta-toast':'Nationwide','uova-pomodoro':'Nationwide',
  'cacio-e-pepe':'Roman',ribollita:'Tuscan','pasta-alla-norma':'Sicilian','pasta-e-fagioli':'Neapolitan',
  'italian-frittata':'Nationwide','yogurt-granola':'Nationwide',
  'coconut-fish-curry':'Coastal',pilau:'Coastal','mishkaki-skewers':'Coastal','maharagwe-nazi':'Coastal',
  'vitumbua-chai':'Zanzibari','bajia-chutney':'Coastal','zanzibar-biryani':'Zanzibari','urojo-soup':'Zanzibari',
  'mahamri-mbaazi':'Zanzibari','viazi-karai':'Coastal','kuku-wa-kupaka':'Coastal',
  'chapati-beef-stew':'Nationwide','chapati-ndengu':'Kamba',
};

Object.assign(recipes, {
  'chapati-beef-stew':{id:'chapati-beef-stew',name:'Chapati & Beef Stew',cuisine:'Kenyan',tagline:'Dinner · Sunday favourite',cost:4.6,protein:34,timeMin:45,ingredients:[{item:'Flour',qty:'1 cup'},{item:'Beef stew meat',qty:'200g'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Carrot',qty:'1'}],steps:['Make a soft chapati dough, rest, roll and fry into layered chapatis.','Brown the beef, then simmer with onion, tomato and carrot into a rich stew.','Serve the stew with warm chapati to scoop.'],note:'The Kenyan Sunday plate — soft, flaky chapati against a slow beef stew.'},
  'chapati-ndengu':{id:'chapati-ndengu',name:'Chapati na Ndengu (Green Gram Stew)',cuisine:'Kenyan',tagline:'Lunch · budget & meat-free',cost:2.8,protein:20,timeMin:40,ingredients:[{item:'Flour',qty:'1 cup'},{item:'Green grams (ndengu)',qty:'1 cup'},{item:'Onion',qty:'1'},{item:'Tomato',qty:'2'},{item:'Coconut milk',qty:'¼ cup'}],steps:['Boil the green grams until soft.','Fry onion and tomato, add the ndengu and a splash of coconut milk; simmer thick.','Serve with warm chapati.'],note:'Chapati with creamy green-gram stew — a hearty, meat-free everyday plate.'},
});

Object.assign(emojiOf, { 'chapati-beef-stew':'🫓','chapati-ndengu':'🫓' });
Object.assign(catOf, { 'Green grams (ndengu)':'Pantry' });
Object.assign(photoMap, {
  'chapati-beef-stew':'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Kenyan_food-chapati_with_beef_stew.jpg/960px-Kenyan_food-chapati_with_beef_stew.jpg',
  'chapati-ndengu':'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Curry-sprouted-green_gram-chickpea.JPG/960px-Curry-sprouted-green_gram-chickpea.JPG',
  muthokoi:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Beans_and_Corn_%28maize%29_porridge.jpg/960px-Beans_and_Corn_%28maize%29_porridge.jpg',
});
cuisineMains.Kenyan.push('chapati-beef-stew','chapati-ndengu');

// Attach region to every recipe that has one.
for (const [id, reg] of Object.entries(REGION)) { if (recipes[id]) recipes[id].region = reg; }
export { REGION };
