// Detailed, expanded methods + prep times + cook's tips, merged over the
// concise base recipes in data.js. Written per dish; quantities scale with the
// servings stepper in the sheet.
export const details = {
  // ---------- neutral breakfasts ----------
  'greek-yogurt-bowl': { prep: 5, steps: [
    'Spoon 1 cup of thick Greek yogurt into a wide bowl and smooth the top.',
    'Rinse ½ cup blueberries and scatter over one half of the bowl.',
    'Add a small handful of almonds and 1 tsp chia seeds for crunch and fibre.',
    'Drizzle 1 tsp honey in a zig-zag and serve straight away, cold.',
  ], tips: ['Use whatever fruit is softening in the fridge — banana, mango or grated apple all work.', 'For extra staying power, stir a scoop of the almonds in rather than only on top.'] },
  'mango-fruit-bowl': { prep: 6, steps: [
    'Peel 1 ripe mango, slice the cheeks off the stone and dice into cubes.',
    'Slice ½ banana into coins.',
    'Spoon ¾ cup Greek yogurt into a bowl and pile the fruit over one side.',
    'Scatter a handful of almonds and finish with 1 tsp honey.',
  ], tips: ['A squeeze of lime over the mango lifts the whole bowl.', 'Freeze over-ripe mango in cubes so you always have some ready.'] },
  'overnight-oats': { prep: 5, steps: [
    'Add ½ cup rolled oats, ½ cup milk and 1 tsp chia seeds to a jar with a lid.',
    'Stir in 1 tbsp peanut butter until it streaks through the oats.',
    'Slice ½ banana on top and press it down into the liquid.',
    'Seal and refrigerate at least 6 hours or overnight.',
    'Eat cold straight from the jar, or loosen with a splash more milk.',
  ], tips: ['Make three jars at once — they keep 3 days in the fridge.', 'Swap peanut butter for a spoon of cocoa and a little more honey for a chocolate version.'] },
  'veggie-omelette': { prep: 4, steps: [
    'Crack 3 eggs into a bowl, season with salt and pepper and whisk until uniform.',
    'Wilt a handful of spinach in a hot non-stick pan with a little oil, then spread it out.',
    'Pour in the eggs, tilt the pan and let them set for about a minute.',
    'Scatter 4 halved cherry tomatoes and 30g crumbled feta over one half.',
    'Fold the omelette over the filling and slide onto the plate.',
  ], tips: ['Keep the heat medium — high heat makes eggs rubbery.', 'Pull the pan off the heat while the centre is just slightly soft; it finishes cooking on the plate.'] },
  'protein-smoothie': { prep: 5, steps: [
    'Add ½ cup Greek yogurt, 1 banana, a handful of spinach and ½ cup blueberries to the blender.',
    'Pour in 1 cup milk and 1 scoop whey protein.',
    'Blend on high for 30–45 seconds until completely smooth, with no flecks of spinach.',
    'Taste and add a little more milk to thin, or a few ice cubes to chill.',
    'Pour into a bottle and go.',
  ], tips: ['Frozen banana makes it thick and cold without watering it down.', 'Add the leaves first and liquid last so the blade catches everything.'] },
  'cottage-toast': { prep: 4, steps: [
    'Toast 1 slice of sourdough until deep golden and crisp.',
    'Fry or poach 1 egg to your liking.',
    'Spread ½ cup cottage cheese thickly over the warm toast.',
    'Top with sliced tomato and the egg, then season with salt and cracked pepper.',
  ], tips: ['A pinch of chilli flakes or everything-bagel seasoning makes it feel like a café plate.', 'Poach the egg in barely-simmering water with a splash of vinegar for a neat shape.'] },
  'chia-pudding': { prep: 5, steps: [
    'Whisk 3 tbsp chia seeds into 1 cup milk with 1 tsp honey in a jar.',
    'Wait 5 minutes, then whisk again to break up any clumps.',
    'Seal and refrigerate overnight until thick and spoonable.',
    'Top with sliced ½ banana and ¼ cup blueberries before eating.',
  ], tips: ['The second whisk after 5 minutes is what stops it setting lumpy.', 'Too thick? Loosen with a splash of milk. Too thin? Add 1 tsp more chia and wait.'] },
  'avocado-toast': { prep: 5, steps: [
    'Toast 1 slice of sourdough until crisp.',
    'Mash ½ avocado with a pinch of salt and a squeeze of lemon if you have it.',
    'Fry or poach 1 egg.',
    'Spread the avocado on the toast, slide the egg on top and add 4 halved cherry tomatoes.',
    'Finish with a pinch of chilli and cracked pepper.',
  ], tips: ['Mash the avocado a little chunky — it holds better than a smooth purée.', 'A runny yolk acts as the sauce, so slightly under-cook it.'] },
  'banana-pancakes': { prep: 5, steps: [
    'Blend ½ cup rolled oats, 2 eggs, 1 banana and ¼ cup milk into a smooth batter.',
    'Rest the batter 5 minutes so the oats absorb the liquid and thicken.',
    'Heat a lightly oiled non-stick pan over medium.',
    'Cook small pancakes 1–2 minutes until bubbles form, then flip and cook 1 minute more.',
    'Stack and drizzle with honey.',
  ], tips: ['Smaller pancakes are far easier to flip than one big one.', 'The riper the banana, the sweeter the pancakes — you may not need extra honey.'] },
  'shakshuka': { prep: 6, steps: [
    'Soften ½ chopped onion and 1 diced bell pepper in oil for 5 minutes.',
    'Stir in 1 tsp cumin and cook 30 seconds until fragrant.',
    'Add 3 chopped tomatoes (or a can), season, and simmer 8–10 minutes into a thick sauce.',
    'Make two wells and crack in 2 eggs; season the tops.',
    'Cover and cook 4–6 minutes until the whites set but the yolks stay soft.',
  ], tips: ['Keep the yolks runny — they should still wobble when you serve.', 'Mop it up with warm bread or leftover chapati.'] },
  'berry-parfait': { prep: 5, steps: [
    'Spoon a third of 1 cup Greek yogurt into a glass.',
    'Add a layer of granola and a few blueberries.',
    'Repeat the yogurt–granola–berry layers twice more.',
    'Finish with almonds and a drizzle of honey.',
  ], tips: ['Assemble just before eating so the granola stays crunchy.', 'For a grab-and-go version, layer it in a jar the night before and keep the granola in a twist of foil on top.'] },

  // ---------- Kenyan ----------
  githeri: { prep: 10, steps: [
    'Heat oil in a pot and fry 1 chopped onion until soft and translucent.',
    'Add 2 chopped tomatoes, 1 diced carrot and 1 tsp cumin; cook down 5 minutes.',
    'Drain and rinse 1 can maize and 1 can kidney beans, then tip them in.',
    'Add a splash of water, season with salt, and simmer 20 minutes, stirring now and then.',
    'Mash a few beans against the side to thicken, and serve hot.',
  ], tips: ['A cubed potato added with the beans makes it more filling.', 'Leftovers fry up beautifully the next day with a little more onion — that’s githeri special.'] },
  'nyama-choma': { prep: 10, steps: [
    'Season 250g beef steak generously with salt and let it sit 10 minutes at room temperature.',
    'Grill or pan-sear over high heat, 3–4 minutes a side, until charred outside and pink within.',
    'While it cooks, dice 1 tomato and ½ red onion and chop a handful of cilantro.',
    'Toss the salad with chopped chilli and a squeeze of lemon — that’s kachumbari.',
    'Rest the meat 5 minutes, slice against the grain, and serve with the kachumbari.',
  ], tips: ['Resting is non-negotiable — cut too early and the juices run out.', 'Slicing against the grain is what keeps each bite tender.'] },
  'sukuma-ugali': { prep: 8, steps: [
    'Boil 2½ cups water, then rain in 1 cup cornmeal a little at a time, stirring hard.',
    'Keep stirring and folding 8–10 minutes until it pulls away from the pan into a stiff ugali; cover and set aside.',
    'Fry 1 chopped onion and 1 tomato in oil until soft.',
    'Add 2 handfuls of shredded collard greens and cook 5 minutes until just tender.',
    'Fry 2 eggs alongside and serve everything together.',
  ], tips: ['Add the cornmeal in a steady stream while stirring to avoid lumps.', 'Don’t overcook the greens — they should stay bright and have a little bite.'] },
  'mukimo-beef': { prep: 15, steps: [
    'Boil 3 peeled potatoes with ½ cup green peas and ½ cup corn until the potato is very soft.',
    'Drain and mash together into a green-flecked mukimo; season with salt.',
    'Separately, brown 200g beef with 1 chopped onion and 2 tomatoes.',
    'Add a splash of water and simmer 20–25 minutes into a thick stew.',
    'Serve a mound of mukimo with a well of stew spooned into the middle.',
  ], tips: ['Traditional mukimo uses pumpkin leaves for colour — spinach works as an easy swap.', 'Mash while hot; it stays smoother.'] },
  'mandazi-chai': { prep: 20, steps: [
    'Mix 1 cup flour, 2 tbsp sugar, a pinch of cardamom and ¼ cup coconut milk into a soft dough.',
    'Knead briefly, cover and rest 20 minutes.',
    'Roll out, cut into triangles, and fry in medium-hot oil until puffed and golden on both sides.',
    'Drain on paper. For the chai, simmer 1 cup milk with tea leaves and a little ginger 3–4 minutes.',
    'Strain the chai and serve hot with the mandazi for dunking.',
  ], tips: ['Oil that’s too hot browns the outside before the middle cooks — test with one first.', 'Cardamom is the signature flavour; don’t skip it.'] },
  'kenyan-uji': { prep: 5, steps: [
    'Whisk ½ cup millet flour with a little cold water into a smooth, lump-free paste.',
    'Bring 2 cups water to a simmer, then stir in the paste.',
    'Cook 8–10 minutes, stirring constantly, until thickened to a pourable porridge.',
    'Loosen with 1 cup milk, sweeten to taste and dust with cinnamon.',
  ], tips: ['Constant stirring is what keeps uji silky rather than lumpy.', 'A squeeze of lemon gives the fermented tang some Kenyans prefer.'] },
  'omena-ugali': { prep: 10, steps: [
    'Rinse 1 cup dried omena well and soak 10 minutes to soften and reduce bitterness.',
    'Fry 1 chopped onion until golden, then add 2 chopped tomatoes and cook to a paste.',
    'Add the drained omena and a splash of water; simmer 10 minutes.',
    'Meanwhile cook ugali: rain 1 cup cornmeal into 2½ cups boiling water, stirring stiff.',
    'Serve the omena with the hot ugali.',
  ], tips: ['The soak is the trick to mellow, non-bitter omena.', 'A pinch of chilli and some cilantro at the end lifts the flavour.'] },
  muthokoi: { prep: 10, steps: [
    'If using dried muthokoi and pigeon peas, soak overnight, then boil together until tender (about 40 min).',
    'Fry 1 chopped onion until soft, add 1 chopped tomato and cook to a paste.',
    'Fold the cooked maize and pigeon peas through the onion-tomato base.',
    'Add a splash of the cooking water, season, and simmer 10 minutes to bring it together.',
  ], tips: ['Canned maize and pigeon peas cut the time right down on a weeknight.', 'A knob of butter stirred in at the end makes it richer.'] },
  'ingokho-stew': { prep: 15, steps: [
    'Brown ½ chicken, cut into pieces, in a little oil until golden on all sides.',
    'Add 2 chopped onions and 2 cloves garlic; cook until soft and fragrant.',
    'Stir in 2 chopped tomatoes and a splash of water.',
    'Cover and simmer gently 30–40 minutes until the chicken is falling-tender.',
    'Finish with chopped cilantro and serve with ugali or rice.',
  ], tips: ['Free-range (kienyeji) chicken needs the longer simmer — don’t rush it.', 'Reduce the sauce uncovered at the end if it’s too thin.'] },
  'mursik-sweet-potato': { prep: 5, steps: [
    'Scrub 1 sweet potato and boil whole until a knife slides through easily, about 20 minutes.',
    'Drain, peel and slice into thick rounds.',
    'Pour a cup of mursik (fermented milk) into a glass.',
    'Serve the warm sweet potato alongside the cool mursik.',
  ], tips: ['Traditionally mursik is aged in a soot-lined gourd — shop-bought fermented milk is the everyday stand-in.', 'Roasting the sweet potato instead of boiling deepens the sweetness.'] },
  'nduma-eggs': { prep: 8, steps: [
    'Peel 250g arrowroot (nduma), cut into chunks and boil until tender, about 15 minutes.',
    'Whisk 2 eggs; soften ½ chopped onion and 1 chopped tomato in a little oil.',
    'Pour in the eggs and scramble gently until just set.',
    'Serve the scrambled eggs over the sliced warm nduma.',
  ], tips: ['Peel arrowroot under running water — the sap can irritate skin.', 'A pinch of chilli in the eggs wakes the whole plate up.'] },
  'kenyan-sweet-potato-eggs': { prep: 6, steps: [
    'Boil 1 peeled, chunked sweet potato and 2 eggs together until the potato is tender.',
    'Lift out the eggs, cool under water and peel.',
    'Wilt a handful of spinach with a little chopped tomato in a pan.',
    'Plate the sweet potato, halved eggs and greens with a pinch of salt.',
  ], tips: ['Cook the eggs 9 minutes for a just-set, creamy yolk.', 'A drizzle of oil and chilli over the top turns it into a fuller meal.'] },
  'kenyan-wet-fry-beef': { prep: 10, steps: [
    'Brown 200g cubed beef in a hot dry pan until well-coloured, then set aside.',
    'Fry 1 sliced onion, 1 bell pepper and 2 tomatoes until soft and jammy.',
    'Return the beef, add a splash of water, and simmer 15–20 minutes until saucy and tender.',
    'Meanwhile cook ugali: 1 cup cornmeal stirred into 2½ cups boiling water until stiff.',
    'Serve the wet fry with the hot ugali.',
  ], tips: ['Browning the beef first, hard and dry, builds the deep flavour.', 'Keep it “wet” — a little clinging sauce, not a soup.'] },
  'chapati-beef-stew': { prep: 20, steps: [
    'Make a soft dough with 1 cup flour, a pinch of salt, a little oil and warm water; knead until smooth and rest 20 minutes.',
    'Divide, roll each piece thin, brush with oil, coil into a spiral and roll out again for flaky layers.',
    'Dry-fry each chapati in a hot pan, a little oil each side, until golden-spotted; keep warm.',
    'For the stew, brown 200g beef, then add 1 onion, 2 tomatoes and 1 carrot with a splash of water.',
    'Simmer 25–30 minutes until the beef is tender and the sauce thick; serve with the chapati.',
  ], tips: ['The oil-and-coil step is what makes chapati flaky rather than flat.', 'Rest the dough — it rolls thinner and cooks softer.'] },
  'chapati-ndengu': { prep: 12, steps: [
    'Boil 1 cup green grams (ndengu) until soft, about 30 minutes (or use canned to save time).',
    'Fry 1 chopped onion and 2 tomatoes into a soft base.',
    'Add the drained ndengu, a splash of coconut milk and a little water; simmer 10 minutes.',
    'Mash a few grams against the pan to thicken and season well.',
    'Serve with warm chapati.',
  ], tips: ['A spoon of coconut milk turns everyday ndengu silky and rich.', 'Cook a big batch of grams and freeze — they reheat perfectly.'] },
  // ---------- pastries ----------
  'blueberry-muffins': { prep: 10, steps: [
    'Heat the oven to 200°C and line a muffin tin with 8 paper cases.',
    'Whisk 1½ cups flour, ½ cup sugar, 2 tsp baking powder and a pinch of salt in a bowl.',
    'In a jug beat 1 egg, ⅓ cup melted butter and ½ cup milk until smooth.',
    'Fold the wet into the dry with a few strokes — lumpy batter is fine — then fold in ¾ cup blueberries.',
    'Divide between the cases and bake 18–20 minutes until domed and springy.',
  ], tips: ['Toss the blueberries in a little flour first so they don’t sink to the bottom.', 'Stop mixing the moment the flour disappears — over-mixing makes muffins tough and peaked.'], storage: 'Keeps 3 days in an airtight tin, or freeze; refresh 10 seconds in the microwave or a few minutes in a warm oven.' },
  'cinnamon-rolls': { prep: 20, steps: [
    'Warm ¾ cup milk, stir in 1 tsp yeast and 1 tbsp sugar, and leave 5 minutes until foamy.',
    'Mix into 2 cups flour with a pinch of salt to a soft dough; knead 8 minutes and rise 1 hour until doubled.',
    'Roll into a rectangle, spread with ¼ cup soft butter, ⅓ cup brown sugar and 1 tbsp cinnamon.',
    'Roll up tightly, slice into 8, and set in a tin to prove 30 minutes.',
    'Bake at 190°C for 20–22 minutes, then drizzle with icing made from powdered sugar and a little milk.',
  ], tips: ['Shape and slice the night before, refrigerate, and just prove and bake in the morning.', 'Use unwaxed dental floss to cut clean slices without squashing the spiral.'], storage: 'Best the day they’re baked; store covered 2 days and warm briefly, or freeze un-iced and ice after reheating.' },
  'cheese-danish': { prep: 8, steps: [
    'Heat the oven to 200°C and line a tray with baking paper.',
    'Cut 1 sheet puff pastry into 6 squares and press a shallow well into each centre with your fingers.',
    'Beat ½ cup cream cheese with 3 tbsp sugar, a little egg yolk and the zest of ½ lemon until smooth.',
    'Spoon the filling into the wells and brush the pastry edges with beaten egg.',
    'Bake 16–18 minutes until the pastry is puffed and deep golden; cool before eating.',
  ], tips: ['Keep the puff pastry cold right up to the oven — warm pastry loses its rise.', 'A dot of jam on the cheese before baking turns it into a fruit danish.'], storage: 'Eat the same day for maximum crispness; keeps 2 days chilled and crisps back up in a hot oven for 5 minutes.' },
  'almond-croissant': { prep: 10, steps: [
    'Heat the oven to 180°C and line a tray with baking paper.',
    'Beat 3 tbsp soft butter with 3 tbsp sugar, then work in ½ cup almond flour and a splash of egg to a paste (frangipane).',
    'Split 2 day-old croissants and, if you like, brush the cut sides with a little sugar syrup.',
    'Fill with frangipane, close, spread a thin layer on top and scatter with flaked almonds.',
    'Bake 12–14 minutes until the almonds are toasted; dust with powdered sugar.',
  ], tips: ['This is the bakery trick for day-old croissants — stale ones actually work best.', 'Make a batch of frangipane and keep it in the fridge for a week of quick almond croissants.'], storage: 'Best warm from the oven; keeps 2 days in a tin and reheats well at 160°C for a few minutes.' },
  'banana-bread': { prep: 12, steps: [
    'Heat the oven to 175°C and grease and line a loaf tin.',
    'Mash 3 very ripe bananas in a large bowl until almost smooth.',
    'Beat in ⅓ cup melted butter, ½ cup sugar and 2 eggs until glossy.',
    'Fold in 1½ cups flour, 1 tsp baking powder and a pinch of salt until just combined.',
    'Pour into the tin and bake 45–50 minutes until a skewer comes out clean; cool before slicing.',
  ], tips: ['The blacker the bananas, the sweeter and moister the loaf.', 'Add a handful of walnuts or chocolate chips with the flour for texture.'], storage: 'Keeps 4 days wrapped at room temperature and freezes beautifully in slices — toast straight from frozen.' },
  // ---------- smoothies & drinks ----------
  'berry-banana-smoothie': { prep: 5, steps: [
    'Add ½ cup Greek yogurt, 1 banana, ½ cup blueberries and ½ cup milk to the blender.',
    'Blend 30–40 seconds until completely smooth and thick.',
    'Taste, add 1 tsp honey if the berries are tart, and pour.',
  ], tips: ['Use frozen banana and berries for a thick, milkshake texture without ice.', 'Too thick? Loosen with a splash more milk; too thin? Add a spoon of oats.'], storage: 'Best within the hour. Pre-portion the fruit into freezer bags so a fresh smoothie is a 2-minute job on busy mornings.' },
  'mango-lassi': { prep: 5, steps: [
    'Peel and cube 1 ripe mango (or use ¾ cup frozen mango).',
    'Blend with 1 cup yogurt and ¼ cup milk until silky.',
    'Add a pinch of cardamom and 1 tsp honey; blend and serve chilled.',
  ], tips: ['A pinch of cardamom is what makes it taste like the restaurant version.', 'Frozen mango gives a thicker, more refreshing lassi than fresh.'], storage: 'Drink fresh; keeps a few hours chilled but thickens — stir or loosen with milk before serving.' },
  'green-smoothie': { prep: 5, steps: [
    'Blend a handful of spinach with 1 banana and a splash of water first, until no green flecks remain.',
    'Add ½ cup Greek yogurt, ½ cup pineapple and 1 tsp chia seeds.',
    'Blend smooth and pour.',
  ], tips: ['Blending the greens with liquid first gives a smooth, not gritty, drink.', 'Pineapple and banana completely mask the spinach — good for greens-sceptics.'], storage: 'Best fresh; the chia will keep thickening, so drink within the hour or add more liquid.' },
  'avocado-smoothie': { prep: 5, steps: [
    'Scoop ½ avocado into the blender with 1 banana and ¾ cup milk.',
    'Blend until velvety and pale green.',
    'Stir in 1 tsp honey and 1 tsp chia; serve cold.',
  ], tips: ['The avocado makes it luxuriously creamy and keeps you full to lunch.', 'A few mint leaves or a squeeze of lime lifts it.'], storage: 'Drink straight away — avocado browns and thickens on standing.' },
  'tropical-smoothie': { prep: 5, steps: [
    'Blend ¾ cup pineapple, ½ mango and ½ banana with ½ cup coconut water.',
    'Squeeze in the juice of ½ lime.',
    'Blend until frothy and pour over ice.',
  ], tips: ['Coconut water keeps it dairy-free and light — swap for coconut milk if you want it richer.', 'Frozen tropical fruit means you can skip the ice.'], storage: 'Best fresh and cold; separates on standing, so give it a stir.' },
  'beet-berry-smoothie': { prep: 6, steps: [
    'Blend ½ cooked beetroot with ½ cup blueberries and ½ cup milk.',
    'Add ½ cup Greek yogurt and 1 tsp honey.',
    'Blend until deep pink and smooth.',
  ], tips: ['Use pre-cooked (vacuum-packed) beetroot to skip the boiling.', 'Berries balance the earthiness — add more if the beet is strong.'], storage: 'Best fresh; keeps half a day chilled. Freeze cooked beetroot in chunks for quick blends.' },
};

// ---------- Swahili (coastal) ----------
Object.assign(details, {
  'coconut-fish-curry': { prep: 8, steps: [
    'Soften ½ chopped onion and 2 chopped tomatoes in a pan until jammy.',
    'Pour in ½ can coconut milk and bring to a gentle simmer — don’t let it boil hard or it splits.',
    'Slide in 1 white fish fillet and spoon sauce over it.',
    'Simmer gently 8 minutes until the fish flakes but still holds together.',
    'Finish with lime juice and chopped cilantro; serve with rice.',
  ], tips: ['Add the fish last and keep the heat low so it stays tender.', 'A little grated ginger and garlic in the base makes it more fragrant.'] },
  pilau: { prep: 12, steps: [
    'Caramelise 1 sliced onion slowly in oil until deep brown — this is the colour of the whole dish.',
    'Add 200g cubed beef and brown, then stir in 1 tbsp pilau masala and 2 cloves garlic until fragrant.',
    'Add a splash of stock and simmer until the beef is nearly tender.',
    'Stir in 1 cup rinsed rice and enough stock to cover by a thumb’s width.',
    'Cover tightly and steam on low 20–25 minutes; fluff with a fork before serving.',
  ], tips: ['Deeply browned onions are the secret to real pilau colour and flavour.', 'Don’t stir once the rice is steaming or it turns sticky.'] },
  'mishkaki-skewers': { prep: 15, steps: [
    'Cube 250g beef and marinate in lemon juice, 2 crushed garlic cloves, a little oil and salt for 20 minutes.',
    'Thread onto skewers, packing the pieces snugly.',
    'Grill or pan-sear over high heat, turning, until charred outside and juicy within, 8–10 minutes.',
    'Toss 1 tomato, ½ red onion and cilantro into a quick kachumbari.',
    'Serve the skewers hot with the salad and extra lemon.',
  ], tips: ['Soak wooden skewers first so they don’t burn.', 'Don’t crowd the pan — the meat should sear, not steam.'] },
  'maharagwe-nazi': { prep: 8, steps: [
    'Fry 1 chopped onion and 2 tomatoes to a soft base.',
    'Pour in ½ can coconut milk and bring to a gentle simmer.',
    'Add 1 can drained kidney beans and cook 12–15 minutes until the sauce thickens.',
    'Mash a few beans to thicken further and season.',
    'Serve scooped up with warm chapati.',
  ], tips: ['Simmer gently once the coconut milk is in so it doesn’t split.', 'Freezes perfectly — make double.'] },
  'vitumbua-chai': { prep: 60, steps: [
    'Batter 1 cup rice flour, ½ cup coconut milk, 2 tbsp sugar and ½ tsp yeast; leave to bubble 1 hour.',
    'Heat a vitumbua or æbleskiver pan with a drop of oil in each cup.',
    'Spoon in batter and cook until the edges crisp and set.',
    'Flip each to brown the domed side.',
    'Simmer 1 cup milk with grated ginger for the chai and serve together.',
  ], tips: ['The yeast rest gives vitumbua their signature tang and lace-crisp edges.', 'A special dimpled pan gives the classic shape, but a small non-stick pan works.'] },
  'bajia-chutney': { prep: 10, steps: [
    'Slice 2 potatoes thinly.',
    'Whisk ½ cup chickpea flour with a pinch of turmeric, chopped chilli, salt and water into a coating batter.',
    'Dip each slice and fry in medium-hot oil until deep golden and crisp.',
    'Drain on paper.',
    'Serve hot with a quick tamarind chutney for dipping.',
  ], tips: ['Batter should coat the back of a spoon — too thin and it slides off.', 'Fry in small batches to keep the oil hot and the bajia crisp.'] },
  'zanzibar-biryani': { prep: 20, steps: [
    'Marinate 2 chicken thighs in ¼ cup yogurt and 1 tbsp biryani masala for 20 minutes.',
    'Fry 1 sliced onion until deep golden and crisp; set half aside for the top.',
    'Cook the chicken in the onion with 1 cubed potato until nearly done.',
    'Parboil 1 cup rice separately until 70% cooked, then drain.',
    'Layer chicken and rice, top with the reserved onions, cover tightly and steam 20 minutes.',
  ], tips: ['Par-cooking the rice, then steaming, keeps every grain separate.', 'A pinch of saffron or turmeric in a little warm milk over the top gives the golden streaks.'] },
  'urojo-soup': { prep: 12, steps: [
    'Boil 2 potatoes until soft; mash some into the broth to thicken it.',
    'Season the broth with mango powder, tamarind and chopped chilli for the signature sour-tang.',
    'Simmer 5 minutes to bring the flavours together.',
    'Ladle into a bowl over the remaining potato chunks.',
    'Top with cassava crisps and any fritters you like.',
  ], tips: ['Balance is everything — keep tasting and adjusting the sour and salt.', 'Add the crisps at the table so they stay crunchy.'] },
  'mahamri-mbaazi': { prep: 40, steps: [
    'Make a dough with 1 cup flour, ½ cup coconut milk, a pinch of cardamom and sugar; rest until risen.',
    'Shape and fry into puffy mahamri, golden on both sides; drain.',
    'For the mbaazi, simmer ¾ cup pigeon peas in coconut milk until creamy.',
    'Season the mbaazi with salt and a little chilli.',
    'Serve the mahamri warm alongside the coconut peas.',
  ], tips: ['Let the dough rise properly — that’s what makes mahamri light.', 'Dunk the mahamri into the mbaazi; that’s the coastal way.'] },
  'viazi-karai': { prep: 10, steps: [
    'Parboil 3 potatoes until just tender, then cool and halve.',
    'Whisk ½ cup chickpea flour with turmeric, chopped chilli, salt and water into a thick batter.',
    'Dip each potato in the turmeric batter to coat.',
    'Fry in medium-hot oil until the shell is golden and crisp.',
    'Serve hot with chilli sauce or tamarind.',
  ], tips: ['Parboil first so the inside is fluffy by the time the shell crisps.', 'Turmeric gives the classic golden colour — don’t leave it out.'] },
  'kuku-wa-kupaka': { prep: 12, steps: [
    'Season 2 chicken thighs and grill or sear until charred and nearly cooked through.',
    'Simmer ½ can coconut milk with 2 crushed garlic cloves, lime juice and chopped chilli 5 minutes.',
    'Nestle the chicken into the sauce and spoon it over the top.',
    'Simmer gently 8–10 minutes until the chicken is cooked and coated.',
    'Serve with rice, spooning the sauce generously.',
  ], tips: ['Char the chicken first — that smoky edge is the point of kuku wa kupaka.', 'Keep the coconut sauce at a bare simmer so it stays glossy.'] },
});

// ---------- Nigerian ----------
Object.assign(details, {
  'jollof-chicken': { prep: 15, steps: [
    'Blend 3 tomatoes, 1 bell pepper and 1 onion into a smooth base.',
    'Fry 2 tbsp tomato paste in oil 2 minutes, then add the blend and cook down 10–12 minutes until reduced and deep red.',
    'Brown 3 chicken thighs; season the sauce with salt and stock.',
    'Stir 1 cup rinsed rice into the sauce with just enough stock to cover.',
    'Cover tightly and steam low 25 minutes until smoky and tender; don’t stir.',
  ], tips: ['Frying the paste and reducing the base hard is what builds real jollof flavour.', 'Letting the bottom catch slightly gives the prized smoky “party jollof” taste.'] },
  'egusi-soup': { prep: 12, steps: [
    'Bloom 1 chopped onion in 2 tbsp palm oil until soft.',
    'Stir ½ cup ground egusi (melon seeds) into a little water to a paste, then fry it in the oil until it crumbles and toasts.',
    'Add 2 chicken thighs and a stock cube with water; simmer 20 minutes.',
    'Stir in 2 handfuls of spinach and cook 5 minutes more.',
    'Serve thick, with rice or a swallow.',
  ], tips: ['Let the egusi fry and clump before adding liquid — that texture is the whole point.', 'Don’t drown it; egusi should be thick, not soupy.'] },
  'efo-riro': { prep: 12, steps: [
    'Blend 1 bell pepper and 1 onion; fry in 2 tbsp palm oil until reduced and deep red.',
    'Add 150g beef and a stock cube with a little water; simmer until tender.',
    'Stir in 2 handfuls of chopped spinach.',
    'Cook 5 minutes just until wilted but still vibrant.',
    'Serve with rice.',
  ], tips: ['Reduce the pepper base well so the stew isn’t watery.', 'Add the greens last — overcooking dulls both colour and flavour.'] },
  'moi-moi-plantain': { prep: 20, steps: [
    'Blend 1 cup soaked black-eyed peas with 1 bell pepper and ½ onion into a smooth, pourable batter.',
    'Season well and pour into greased cups or ramekins.',
    'Press a boiled egg into each and steam 35 minutes until set and springy.',
    'Slice 1 plantain and fry until caramelised and golden.',
    'Turn out the moi moi and serve with the plantain.',
  ], tips: ['Peeling the soaked peas gives the smoothest moi moi, but a good blender helps.', 'It’s set when a knife comes out clean.'] },
  'akara-pap': { prep: 15, steps: [
    'Blend 1 cup soaked black-eyed peas with ¼ onion and chopped chilli into a thick, fluffy batter.',
    'Beat the batter by hand a minute to aerate it — that makes akara light.',
    'Fry spoonfuls in medium-hot oil until deep golden and crisp; drain.',
    'For the pap, whisk ½ cup fine cornmeal into simmering water until smooth and thick.',
    'Sweeten the pap lightly and serve hot with the akara.',
  ], tips: ['Aerating the batter is the difference between fluffy and dense akara.', 'The oil must be properly hot or the akara drink it up.'] },
  'yam-egg-sauce': { prep: 8, steps: [
    'Peel and cube 300g yam; boil in salted water until tender, about 15 minutes.',
    'Soften ½ chopped onion, ½ bell pepper and 1 tomato in oil.',
    'Pour in 2 whisked eggs and stir gently into a soft, saucy scramble.',
    'Season the sauce and drain the yam.',
    'Serve the boiled yam with the egg sauce spooned over.',
  ], tips: ['Don’t over-cook the eggs — pull them off while still glossy.', 'A pinch of curry powder in the sauce is a popular touch.'] },
  'nigerian-fried-yam-eggs': { prep: 8, steps: [
    'Peel and cut 300g yam into batons; parboil 5 minutes, then drain and dry.',
    'Fry the yam in hot oil until crisp and golden; drain on paper.',
    'Make a peppery sauce with 2 tomatoes, ½ onion and chopped chilli.',
    'Stir 2 whisked eggs through the sauce until just set.',
    'Serve the fried yam with the egg sauce.',
  ], tips: ['Drying the parboiled yam gives a crisper fry.', 'Salt the yam the moment it comes out of the oil.'] },
  'plantain-frittata': { prep: 8, steps: [
    'Slice 1 plantain and fry until caramelised and golden; spread over the pan base.',
    'Whisk 3 eggs with ½ chopped bell pepper, ½ onion and 1 tomato; season.',
    'Pour over the plantain and cook on low until the edges set.',
    'Cover 3–4 minutes to set the top, or finish under a grill.',
    'Slice into wedges like a frittata.',
  ], tips: ['Let the plantain caramelise fully first — that sweetness carries the dish.', 'Low heat keeps the eggs soft rather than rubbery.'] },
  'amala-ewedu': { prep: 10, steps: [
    'Blend 2 handfuls jute leaves (ewedu) with a little water; simmer with locust beans and a stock cube until silky.',
    'Boil water and whisk in 1 cup yam flour a little at a time, stirring hard.',
    'Keep folding 3–4 minutes until smooth and stretchy — that’s amala.',
    'Shape the amala into a mound.',
    'Serve with the ewedu spooned over, and a pepper stew if you like.',
  ], tips: ['Add the yam flour gradually and stir constantly to avoid lumps.', 'A traditional ewedu broom or a quick blitz gives the signature silky texture.'] },
  'ofe-nsala': { prep: 15, steps: [
    'Season 1 white fish fillet and simmer gently in water until just cooked; lift out.',
    'Grate or pound 200g yam and stir into the broth to thicken it — this makes the “white soup”.',
    'Add ground crayfish, chopped chilli and 1 onion; simmer 10 minutes.',
    'Return the fish gently so it doesn’t break.',
    'Serve hot on its own or with a swallow.',
  ], tips: ['No palm oil here — the pale, peppery broth is the whole identity of nsala.', 'Add the fish back at the very end to keep it whole.'] },
  'tuwo-kuka': { prep: 12, steps: [
    'Cook 1 cup rice until very soft, then mash and beat into a smooth, stiff tuwo.',
    'Simmer 2 tbsp baobab-leaf powder (kuka) with dried fish, 1 onion and a stock cube into a soup.',
    'Cook until it thickens to a silky, slightly ropy consistency.',
    'Shape the tuwo into a mound.',
    'Serve with the kuka soup ladled over.',
  ], tips: ['Whisk the kuka in slowly so it doesn’t clump.', 'Pounded rice (tuwo shinkafa) should be smooth with no visible grains.'] },
  'suya-skewers': { prep: 15, steps: [
    'Slice 220g beef thinly against the grain and thread onto skewers.',
    'Coat generously in suya spice (yaji), pressing it into the meat.',
    'Grill hot and fast, 2–3 minutes a side, until charred at the edges.',
    'Dust with a little more yaji straight off the heat.',
    'Serve with sliced onion, tomato and cabbage.',
  ], tips: ['Thin slices cook fast and soak up the yaji best.', 'A second dusting of spice off the grill makes it punchy.'] },
  'ofada-stew': { prep: 15, steps: [
    'Blend 2 green bell peppers, chilli and 1 onion; fry hard in 2 tbsp palm oil until reduced and darkened.',
    'Add 180g beef and a stock cube with a little water; simmer until tender.',
    'Cook until the oil rises and the sauce is thick and rich (ayamase).',
    'Steam 1 cup ofada-style rice separately.',
    'Serve the rice with the green pepper stew.',
  ], tips: ['Bleaching a little palm oil first gives the classic dark ayamase, but reducing hard works too.', 'It’s meant to be oily and intense — go bold on the pepper.'] },
});

// ---------- Ugandan ----------
Object.assign(details, {
  'matoke-groundnut': { prep: 15, steps: [
    'Peel 4 green bananas (matoke) — rub with oil first to stop them staining your hands.',
    'Simmer the matoke in a little water until just tender, about 15 minutes.',
    'Make a groundnut sauce: soften 1 onion and 2 tomatoes, then stir in 2 tbsp peanut butter loosened with water.',
    'Fold the matoke through the sauce and simmer 5 minutes to absorb the flavour.',
    'Top with a boiled egg for protein and serve.',
  ], tips: ['Oil your hands and knife before peeling matoke — the sap is sticky.', 'Loosen the peanut butter with warm water off the heat so it doesn’t seize.'] },
  'luwombo-chicken': { prep: 15, steps: [
    'Brown 2 chicken thighs with 1 onion, 1 bell pepper and 2 tomatoes.',
    'Stir in 1 tbsp peanut butter loosened with a little stock.',
    'Traditionally this is wrapped in banana leaves; for the stovetop, cover tightly instead.',
    'Steam on low heat 30 minutes until the chicken is falling-tender and the sauce rich.',
    'Serve with matoke, rice or posho.',
  ], tips: ['Low and slow is the whole idea — luwombo is a gentle steam, not a fast fry.', 'Banana-leaf parcels add aroma if you can find them.'] },
  'beef-posho': { prep: 12, steps: [
    'Brown 200g beef, then add 1 onion, 2 tomatoes and 1 carrot with a splash of water.',
    'Simmer 25–30 minutes until the beef is tender and the sauce thick.',
    'For the posho, boil 2½ cups water and whisk in 1 cup cornmeal.',
    'Stir hard 8–10 minutes until stiff and smooth, pressing out any lumps.',
    'Serve the posho alongside a ladle of stew.',
  ], tips: ['Posho and ugali are the same technique — keep stirring for a smooth finish.', 'A splash of the stew’s sauce over the posho makes each bite better.'] },
  'doodo-groundnut': { prep: 10, steps: [
    'Wash and roughly chop 2 handfuls of amaranth greens (doodo).',
    'Soften 1 onion and 1 tomato in a pan.',
    'Add the greens and cook down 5 minutes until wilted.',
    'Stir in 2 tbsp peanut butter loosened with water and simmer 5 minutes into a silky sauce.',
    'Top with a boiled egg and serve with posho or sweet potato.',
  ], tips: ['Add the peanut butter at the end so it stays creamy, not grainy.', 'Any tender leafy green works if you can’t find amaranth.'] },
  'rolex-wrap': { prep: 6, steps: [
    'Whisk 2 eggs with shredded cabbage, chopped tomato and onion; season.',
    'Fry the mix into a flat omelette in a little oil.',
    'Warm 1 chapati in the same pan until soft and pliable.',
    'Lay the omelette on the chapati.',
    'Roll it up tight and slice, or eat whole on the move.',
  ], tips: ['Warm the chapati so it rolls without cracking.', 'A line of chilli sauce before rolling is how it’s sold on the street.'] },
  katogo: { prep: 12, steps: [
    'Brown 100g beef with 1 onion and 1 tomato in a pot.',
    'Peel and chunk 3 green bananas (matoke).',
    'Add the matoke and a splash of stock; cover and simmer until soft, about 20 minutes.',
    'Mash slightly so the matoke soaks up the stew.',
    'Serve hot as a hearty breakfast.',
  ], tips: ['Katogo is meant to be soft and stew-like — a light mash brings it together.', 'Offal or beans are common swaps for the beef.'] },
  'eshabwe-kalo': { prep: 10, steps: [
    'Boil 2 cups water and whisk in 1 cup millet flour a little at a time.',
    'Stir hard until stiff and smooth to make the kalo (millet bread); shape into a mound.',
    'Warm 3 tbsp ghee gently with ½ cup milk and a little grated onion.',
    'Whisk until it emulsifies into a rich, pale sauce — that’s eshabwe.',
    'Serve the kalo with the eshabwe for dipping.',
  ], tips: ['Keep the ghee sauce warm and whisk to keep it emulsified.', 'Kalo is stiffer than porridge — add the flour steadily and beat well.'] },
  malakwang: { prep: 12, steps: [
    'Wash 2 handfuls of malakwang (sour greens) and simmer until tender.',
    'Toast 1 tbsp sesame (simsim) and grind or crush lightly.',
    'Stir 2 tbsp peanut butter and the simsim into the greens with a little water.',
    'Simmer 5 minutes into a nutty, tangy sauce.',
    'Serve with posho, sweet potato or millet bread.',
  ], tips: ['The sourness of the greens is the signature — balance it, don’t hide it.', 'Toasting the simsim first deepens the nutty flavour.'] },
  kabalagala: { prep: 12, steps: [
    'Mash 2 very ripe plantains until smooth.',
    'Mix in ½ cup flour, 2 tbsp toasted sesame and 1 tbsp sugar into a thick batter.',
    'Shape into small flat rounds.',
    'Fry in medium-hot oil until golden and cooked through, turning once.',
    'Drain and serve warm.',
  ], tips: ['The plantains must be very ripe — that’s the only sweetness.', 'Keep them small and thin so the centres cook before the outsides darken.'] },
  'ugandan-millet-porridge': { prep: 5, steps: [
    'Whisk ½ cup millet flour with cold water into a smooth paste.',
    'Bring 2 cups water to a simmer and stir in the paste.',
    'Cook 8–10 minutes, stirring, until thickened.',
    'Loosen with 1 cup milk, sweeten to taste and stir in a little toasted simsim.',
  ], tips: ['A smooth cold-water paste first is the anti-lump trick.', 'A squeeze of lemon gives the traditional fermented tang.'] },
  'ugandan-groundnut-chicken': { prep: 12, steps: [
    'Brown 2 chicken thighs with 1 onion, 2 tomatoes and 1 bell pepper.',
    'Add a splash of stock and simmer until the chicken is nearly tender.',
    'Loosen 2 tbsp peanut butter with warm stock and stir it in.',
    'Simmer gently 8–10 minutes until the sauce is thick and silky.',
    'Serve with rice, matoke or posho.',
  ], tips: ['Stir the peanut butter in off a hard boil so the sauce stays smooth.', 'Thin with a little more stock if it tightens too much.'] },
});

// ---------- Indian ----------
Object.assign(details, {
  'chicken-tikka': { prep: 20, steps: [
    'Cube 2 chicken breasts and marinate in ½ cup yogurt with 1 tbsp garam masala for 20 minutes (longer is better).',
    'Sear the chicken in a hot pan until charred at the edges; set aside.',
    'Fry 1 onion, then add 3 blended tomatoes and cook down 10 minutes into a thick sauce.',
    'Stir the chicken back in with a splash of water and simmer 5 minutes.',
    'Serve over rice; save half for tomorrow’s lunch.',
  ], tips: ['A long yogurt marinade tenderises the chicken and deepens the char.', 'A splash of cream or a knob of butter at the end makes it restaurant-rich.'] },
  'chana-masala': { prep: 10, steps: [
    'Fry 1 onion, 1 thumb ginger and 2 garlic cloves into a soft paste.',
    'Add 2 chopped tomatoes and 1 tbsp garam masala; cook down 8 minutes until the oil separates.',
    'Tip in 1 can chickpeas with a splash of water.',
    'Simmer 15 minutes, mashing a few chickpeas to thicken the sauce.',
    'Finish with a squeeze of lemon and serve with rice or roti.',
  ], tips: ['Cooking the masala until the oil separates is the key flavour step.', 'A pinch of amchur (mango powder) or lemon gives the classic tang.'] },
  'dal-tadka': { prep: 8, steps: [
    'Rinse ¾ cup red lentils and simmer with water and a pinch of turmeric until soft and broken down, 15–20 minutes.',
    'In a small pan, heat oil or ghee and fry 1 tsp cumin, 2 garlic cloves and 1 chopped onion until golden.',
    'Pour the sizzling tempering (tadka) over the cooked dal.',
    'Stir through and season; simmer 2 minutes.',
    'Serve with cumin rice.',
  ], tips: ['The tadka poured over at the end is what makes dal special — don’t skip it.', 'Whisk the dal briefly for a creamier texture.'] },
  'palak-paneer': { prep: 12, steps: [
    'Blanch 2 handfuls spinach 30 seconds, then blend to a smooth purée (a quick ice bath keeps it green).',
    'Fry 1 onion, 2 garlic cloves and 1 tomato until soft.',
    'Add the spinach purée and simmer 5 minutes; season.',
    'Fold in 150g cubed paneer and warm through 3 minutes.',
    'Serve with roti.',
  ], tips: ['Blanch, don’t boil, the spinach — it keeps the vivid green colour.', 'Lightly pan-fry the paneer first if you like a firmer bite.'] },
  'veg-upma': { prep: 6, steps: [
    'Dry-toast ¾ cup semolina in a pan until fragrant and pale gold; set aside.',
    'Fry ½ tsp mustard seeds until they pop, then add ½ onion and 1 diced carrot.',
    'Pour in 1½ cups hot water and season; bring to a simmer.',
    'Rain in the semolina slowly, stirring hard to avoid lumps.',
    'Cook 2 minutes until fluffy and the water is absorbed.',
  ], tips: ['Toasting the semolina keeps the upma fluffy, not gluey.', 'Add the hot water carefully — it will splutter.'] },
  'besan-chilla': { prep: 6, steps: [
    'Whisk 1 cup chickpea flour with water into a smooth, pourable batter.',
    'Stir in chopped onion, tomato, chilli and ½ tsp cumin; season.',
    'Ladle onto a hot, lightly oiled griddle and spread into a thin round.',
    'Cook 2 minutes until the edges lift, then flip and cook 1 minute more.',
    'Serve hot with chutney.',
  ], tips: ['Rest the batter 5 minutes for a smoother chilla.', 'Keep it thin — thick chilla stays doughy in the middle.'] },
  'sarson-makki': { prep: 15, steps: [
    'Simmer 2 handfuls mustard greens and 1 handful spinach with ginger and garlic until very soft.',
    'Blend coarsely, then cook down until thick — this is sarson da saag.',
    'Season and finish with a knob of butter or ghee.',
    'Mix 1 cup corn flour (makki) with warm water into a dough and pat into flatbreads.',
    'Griddle the makki roti and serve with the saag.',
  ], tips: ['Slow-cooking the greens is what mellows their bite.', 'Makki roti is delicate — pat it out on a sheet of plastic to shape it.'] },
  'sambar-rice': { prep: 10, steps: [
    'Simmer ½ cup red lentils with 1 diced carrot until soft.',
    'Add 1 chopped onion, 1 tbsp tamarind paste and 1 tbsp sambar powder.',
    'Simmer 10 minutes until it thickens into a tangy, spiced stew.',
    'Temper mustard seeds in a little oil and stir through (optional but classic).',
    'Serve hot over steamed rice.',
  ], tips: ['Tamarind gives sambar its signature sour edge — adjust to taste.', 'It freezes and reheats beautifully.'] },
  'gujarati-khichdi': { prep: 5, steps: [
    'Rinse ½ cup rice and ½ cup red lentils together until the water runs clear.',
    'Add a pinch of turmeric and plenty of water (about 3×).',
    'Simmer 20 minutes, stirring occasionally, until soft and porridge-like.',
    'Temper ½ tsp cumin in 1 tbsp ghee and stir through.',
    'Season and serve hot, loosening with water if needed.',
  ], tips: ['Khichdi should be soft and comforting — err on the side of more water.', 'A dollop of yogurt or pickle on the side is traditional.'] },
  'bengali-fish-curry': { prep: 12, steps: [
    'Lightly fry 1 cubed potato and 1 white fish fillet until golden; set the fish aside so it doesn’t break.',
    'Fry ½ tsp mustard seeds, then add 1 chopped tomato and a pinch of turmeric.',
    'Add water and simmer until the potato is tender.',
    'Slip the fish back in and simmer 5 minutes in the light, spiced broth.',
    'Serve over steamed rice.',
  ], tips: ['Fry the fish gently and add it back at the end so it stays whole.', 'Mustard oil, if you have it, gives the authentic Bengali punch.'] },
  'masala-omelette': { prep: 4, steps: [
    'Whisk 3 eggs with ½ chopped onion, 1 tomato, chopped chilli and cilantro; season.',
    'Heat a little oil in a non-stick pan over medium.',
    'Pour in the mix and let it set for a minute.',
    'Lift the edges and tilt so the runny egg flows underneath.',
    'Fold and slide out when just set but still soft.',
  ], tips: ['Finely chop the onion so it softens in the quick cook.', 'A pinch of turmeric gives colour and warmth.'] },
  poha: { prep: 6, steps: [
    'Rinse 1 cup poha (flattened rice) in a sieve until just soft, then drain — don’t let it go mushy.',
    'Fry ½ tsp mustard seeds, then ½ onion and 1 diced potato until soft.',
    'Add a pinch of turmeric and a splash of water to cook the potato through.',
    'Fold the poha through gently and warm 2 minutes.',
    'Finish with lemon and cilantro.',
  ], tips: ['Rinse-and-drain, not soak — poha turns to paste if it sits in water.', 'Fold gently so the flakes stay separate.'] },
  'rajma-rice': { prep: 10, steps: [
    'Fry 1 onion until golden, then add 2 blended tomatoes and 1 tbsp garam masala.',
    'Cook down 8–10 minutes until the masala is thick and the oil separates.',
    'Add 1 can kidney beans with a splash of water.',
    'Simmer 15 minutes, mashing a few beans to thicken the gravy.',
    'Serve over steamed rice.',
  ], tips: ['Mashing some beans is the trick to a thick, clingy rajma gravy.', 'A knob of butter stirred in at the end rounds it out.'] },
});

// ---------- Italian ----------
Object.assign(details, {
  'spaghetti-bolognese': { prep: 10, steps: [
    'Finely dice 1 onion and 1 carrot and soften in oil 5 minutes.',
    'Add 200g ground beef and brown well, breaking up the lumps.',
    'Add 3 chopped tomatoes (or a can) and a splash of water; season.',
    'Simmer at least 20 minutes — longer is better — into a rich ragù.',
    'Toss with cooked spaghetti and grate over parmesan.',
  ], tips: ['Brown the beef properly before the tomato goes in — that’s the flavour base.', 'A double batch of ragù freezes and becomes three different dinners.'] },
  'pesto-chicken-pasta': { prep: 6, steps: [
    'Boil 80g pasta in well-salted water until al dente; save a little pasta water.',
    'Sear 1 sliced chicken breast until golden and cooked through.',
    'Drain the pasta and toss with 2 tbsp pesto, loosening with a splash of pasta water.',
    'Fold in the chicken and 6 halved cherry tomatoes.',
    'Finish with parmesan.',
  ], tips: ['Toss the pesto off the heat so it stays fresh and green.', 'That splash of starchy pasta water makes the sauce cling.'] },
  'minestrone-crostini': { prep: 12, steps: [
    'Soften 1 diced onion and 1 carrot in oil.',
    'Add 2 chopped tomatoes and a splash of stock; simmer 10 minutes.',
    'Add 1 can kidney beans and ½ cup small pasta; cook until the pasta is tender.',
    'Season and loosen with more stock to a soup consistency.',
    'Toast bread, top with parmesan, and serve the crostini alongside.',
  ], tips: ['Any odd vegetables in the fridge belong in minestrone.', 'It thickens as it sits — keep a little stock to loosen leftovers.'] },
  'chicken-parmigiana': { prep: 15, steps: [
    'Butterfly 1 chicken breast, coat in ½ cup breadcrumbs and pan-fry until golden and crisp both sides.',
    'Simmer 2 chopped tomatoes into a quick sauce.',
    'Top the chicken with sauce, 50g mozzarella and 3 tbsp parmesan.',
    'Melt under a hot grill until bubbling and golden.',
    'Serve with a handful of wilted greens.',
  ], tips: ['Get the crumb crisp before saucing so it doesn’t go soggy.', 'Pound the breast even so it cooks through by the time it’s golden.'] },
  'ricotta-toast': { prep: 4, steps: [
    'Toast 1 slice of sourdough until golden.',
    'Spread ½ cup ricotta thickly over the warm toast.',
    'Drizzle with 1 tsp honey.',
    'Scatter a handful of walnuts and a little cracked pepper.',
  ], tips: ['Whip the ricotta with a fork first for a lighter, creamier spread.', 'Swap honey for jam or sliced pear to change it up.'] },
  'uova-pomodoro': { prep: 5, steps: [
    'Simmer 3 crushed tomatoes with 1 sliced garlic clove until thick, 8–10 minutes.',
    'Season and make two small wells in the sauce.',
    'Crack in 2 eggs and cover the pan.',
    'Cook 4–6 minutes until the whites set and the yolks stay soft.',
    'Finish with parmesan and mop up with toasted sourdough.',
  ], tips: ['Keep the yolks runny — they’re the sauce.', 'A pinch of chilli turns it into eggs “in purgatory”.'] },
  'cacio-e-pepe': { prep: 5, steps: [
    'Boil 80g spaghetti in well-salted water, saving a full cup of starchy water.',
    'Toast 1 tsp cracked black pepper in a dry pan 30 seconds.',
    'Off the heat, add a ladle of pasta water and 40g finely grated pecorino, whisking to a cream.',
    'Add the drained pasta and toss vigorously, splashing in more water until silky.',
    'Plate immediately, twirled high.',
  ], tips: ['Off the heat is essential — too hot and the cheese clumps.', 'Finely grate the pecorino so it melts into a smooth sauce.'] },
  ribollita: { prep: 12, steps: [
    'Soften 1 onion and 1 carrot in oil.',
    'Add 2 chopped tomatoes and 1 can kidney beans with a splash of water.',
    'Simmer 20 minutes, mashing some beans to thicken.',
    'Tear in 2 slices of stale bread and stir until it breaks down and thickens the soup.',
    'Rest 5 minutes, drizzle with oil, and serve.',
  ], tips: ['Stale bread is the point — it thickens ribollita into its hearty texture.', 'It’s even better reheated the next day (that’s what “ribollita” means).'] },
  'pasta-alla-norma': { prep: 10, steps: [
    'Cube 1 eggplant, salt briefly, then fry in oil until golden and soft; set aside.',
    'Simmer 3 chopped tomatoes with 1 garlic clove into a quick sauce.',
    'Fold the eggplant back into the sauce.',
    'Toss with 80g cooked pasta.',
    'Finish with a spoon of ricotta and a little basil if you have it.',
  ], tips: ['Fry the eggplant until truly golden — pale eggplant stays bitter and spongy.', 'Salted ricotta (ricotta salata) is the classic finish.'] },
  'pasta-e-fagioli': { prep: 8, steps: [
    'Soften 1 garlic clove in oil, then add 2 chopped tomatoes and 1 can kidney beans with water.',
    'Simmer 15 minutes, mashing some beans to thicken the broth.',
    'Add 60g small pasta directly to the pot with a little more water.',
    'Cook until the pasta is tender and the whole thing is thick and stewy.',
    'Finish with parmesan and a drizzle of oil.',
  ], tips: ['Cooking the pasta in the soup makes it silky and thick.', 'Keep it loose while cooking — the pasta drinks up liquid as it stands.'] },
  'italian-frittata': { prep: 8, steps: [
    'Fry 1 sliced potato and ½ onion in oil until soft and golden.',
    'Add a handful of spinach and let it wilt.',
    'Whisk 3 eggs with 2 tbsp parmesan; season and pour over.',
    'Cook on low until the edges set, then cover 3–4 minutes to set the top.',
    'Slide out and slice into wedges.',
  ], tips: ['Low heat keeps the frittata tender all the way through.', 'Great cold in a lunchbox the next day.'] },
  'yogurt-granola': { prep: 4, steps: [
    'Spoon 1 cup yogurt into a bowl.',
    'Scatter ⅓ cup granola and a handful of walnuts over the top.',
    'Add a few blueberries.',
    'Drizzle with 1 tsp honey and serve.',
  ], tips: ['Add the granola just before eating so it stays crunchy.', 'Toast the walnuts for a minute to bring out their flavour.'] },
  'tuna-white-bean-salad': { prep: 8, steps: [
    'Drain 1 can tuna and 1 can kidney beans and add to a bowl.',
    'Thinly slice ½ red onion and add with a handful of chopped cilantro or parsley.',
    'Dress with the juice of ½ lemon, a good glug of olive oil, salt and pepper.',
    'Toss gently so the beans don’t break.',
    'Rest 5 minutes for the flavours to mingle, then serve.',
  ], tips: ['Let it sit a few minutes — the beans soak up the lemon and oil.', 'A pinch of chilli or some capers lifts it further.'] },
});

// ---------- more plant-based mains ----------
Object.assign(details, {
  'aloo-gobi': { prep: 10, steps: [
    'Cube 2 potatoes and break ½ a cauliflower into small florets.',
    'Fry the potato in a little oil with 1 tsp cumin seeds until the edges turn golden.',
    'Add the cauliflower, 2 chopped tomatoes, 1 tsp turmeric, chilli and salt.',
    'Cover and steam on low 15–18 minutes, stirring gently, until both are tender but not mushy.',
    'Finish with fresh coriander and serve over steamed rice.',
  ], tips: ['Keep it dry — add water a splash at a time only if it catches.', 'Cut the potato slightly smaller than the cauliflower so they finish together.'], storage: 'Keeps 3 days chilled and reheats well; the flavours deepen overnight. Freeze without the rice.' },
  'baingan-bharta': { prep: 12, steps: [
    'Char 1 large eggplant whole over a gas flame or under the grill, turning, until the skin blackens and the flesh collapses.',
    'Cool, peel off the skin and mash the smoky flesh.',
    'Fry 1 chopped onion, 2 cloves garlic and 2 tomatoes into a soft masala with cumin and chilli.',
    'Stir the mashed eggplant through and cook 5 minutes to bring it together.',
    'Serve with steamed rice.',
  ], tips: ['The flame-charring is what gives bharta its signature smoke — don’t skip it.', 'No gas hob? Roast the whole eggplant at 220°C until collapsed.'], storage: 'Keeps 3 days chilled; reheat gently. Freezes well for a month.' },
  'chickpea-cauliflower-curry': { prep: 8, steps: [
    'Soften 1 chopped onion and 2 tomatoes in a pan.',
    'Add ½ cauliflower in florets with a splash of water and cook 5 minutes.',
    'Tip in 1 can drained chickpeas and ½ cup coconut milk; simmer 12–15 minutes until the cauliflower is tender.',
    'Season well and serve over steamed rice.',
  ], tips: ['A squeeze of lime at the end brightens the coconut.', 'Use the starchy chickpea liquid (aquafaba) instead of water for a richer sauce.'], storage: 'Keeps 4 days chilled and reheats beautifully — a strong batch-cook. Freeze without the rice.' },
  'beans-matoke': { prep: 12, steps: [
    'Peel 4 green bananas (matoke) and steam or boil until soft, 20–25 minutes.',
    'Meanwhile fry 1 onion and 2 tomatoes, add 1 can kidney beans and ¼ cup coconut milk.',
    'Simmer 15 minutes, mashing a few beans to thicken the stew.',
    'Serve the beans spooned over the matoke.',
  ], tips: ['A little mashed matoke stirred into the beans thickens everything nicely.', 'Rub oil on your hands before peeling matoke — the sap stains.'], storage: 'Beans keep 4 days and freeze well; steam fresh matoke to serve.' },
});

// ---------- more pastries + drinks ----------
Object.assign(details, {
  'pain-au-chocolat': { prep: 8, steps: [
    'Heat the oven to 200°C and line a tray with baking paper.',
    'Cut 1 sheet puff pastry into rectangles and lay a line of chopped dark chocolate (about 40g total) along one short edge of each.',
    'Roll up around the chocolate and set seam-side down.',
    'Brush with beaten egg and a little sugar, and bake 16–18 minutes until puffed and deep golden.',
  ], tips: ['Keep the pastry cold until it hits the oven — that’s what makes it flaky.', 'Two thin bars of chocolate spaced apart give the classic double-spiral.'], storage: 'Best warm the day they’re baked; re-crisp in a hot oven for a few minutes. Freeze shaped and unbaked, then bake from frozen.' },
  'cream-scones': { prep: 10, steps: [
    'Heat the oven to 210°C. Rub ¼ cup cold butter into 2 cups flour, 2 tbsp sugar and 1 tbsp baking powder until it looks like breadcrumbs.',
    'Stir in just enough milk (about ½ cup) to bring it to a soft dough — don’t overwork it.',
    'Pat out 3cm thick and cut rounds with a floured cutter.',
    'Brush the tops with milk and bake 12–14 minutes until risen and golden. Serve with jam.',
  ], tips: ['Handle the dough as little as possible for a light, tall scone.', 'Push the cutter straight down without twisting so they rise evenly.'], storage: 'Best the day they’re made; refresh next-day scones for 5 minutes in a warm oven. Freeze well.' },
  'puff-puff': { prep: 12, steps: [
    'Whisk 2 cups flour, 1 tsp yeast, ⅓ cup sugar and a pinch of nutmeg with warm water into a thick, sticky batter.',
    'Cover and leave somewhere warm about 1 hour, until bubbly and risen.',
    'Heat oil for deep-frying. Scoop rounds of batter in with a wet hand or spoon.',
    'Fry, turning, until deep golden all over; drain and dust with a little sugar.',
  ], tips: ['The batter should be thicker than pancake batter but still drop from a spoon.', 'Medium heat — too hot and they brown before the middle cooks.'], storage: 'Best eaten warm and fresh; they soften as they sit. Re-crisp briefly in a hot oven.' },
  'chocolate-peanut-smoothie': { prep: 5, steps: [
    'Add 1 cup milk, 1 banana, 2 tbsp peanut butter and 1 tbsp cocoa to the blender.',
    'Blend 30 seconds until smooth and frothy.',
    'Sweeten with 1 tsp honey and pour over ice.',
  ], tips: ['A frozen banana turns it into a thick shake.', 'A pinch of salt makes the peanut and chocolate pop.'], storage: 'Best fresh; pre-portion banana and peanut butter into the freezer for a 2-minute blend.' },
  'orange-carrot-juice': { prep: 6, steps: [
    'Blend 2 chopped carrots with a splash of water until fine, then strain through a sieve.',
    'Squeeze in the juice of 2 oranges and ½ lemon.',
    'Grate in a little ginger, stir and serve cold.',
  ], tips: ['No juicer needed — blend and strain works fine.', 'Chill the fruit first for a colder, fresher juice.'], storage: 'Drink within a few hours; fresh juice separates and dulls on standing — stir before serving.' },
  'strawberry-shake': { prep: 5, steps: [
    'Add ½ cup Greek yogurt, 1 cup strawberries, ½ cup milk and 2 tbsp oats to the blender.',
    'Blend until completely smooth.',
    'Sweeten with 1 tsp honey and drink chilled.',
  ], tips: ['The oats thicken it and add staying power without changing the flavour.', 'Frozen strawberries make it thick and frosty — skip the ice.'], storage: 'Best fresh; the oats keep thickening, so drink within the hour or loosen with milk.' },
});

// ---- Make-ahead & storage notes, merged into details above ----
const STORAGE = {
  // neutral breakfasts
  'greek-yogurt-bowl': 'Best assembled fresh. Keep yogurt, fruit and toppings separate and build in seconds each morning.',
  'mango-fruit-bowl': 'Best fresh. Pre-cut mango keeps 2 days in an airtight box, or freeze cubes for months.',
  'overnight-oats': 'Made ahead by design — keeps 3 days covered in the fridge. Build three jars at once.',
  'veggie-omelette': 'Best straight from the pan; egg goes rubbery reheated. Prep the fillings the night before.',
  'protein-smoothie': 'Best drunk fresh. Bag the fruit and spinach in the freezer as ready “smoothie kits”.',
  'cottage-toast': 'Assemble fresh so the toast stays crisp; the cottage cheese keeps a week in the tub.',
  'chia-pudding': 'A make-ahead star — keeps 4 days in the jar. Add fresh fruit just before eating.',
  'avocado-toast': 'Best made fresh (avocado browns). Squeeze lemon on cut avocado to hold it a day.',
  'banana-pancakes': 'Keep 2 days chilled or freeze between parchment; reheat in a toaster or dry pan.',
  'shakshuka': 'The sauce keeps 3 days and freezes 2 months — just crack in fresh eggs when reheating.',
  'berry-parfait': 'Assemble fresh so the granola stays crunchy, or jar it overnight with granola kept separate.',
  // Kenyan
  githeri: 'Keeps 3 days chilled and freezes 3 months. Even better fried up the next day as githeri special.',
  'nyama-choma': 'Best fresh off the grill. Leftover meat keeps 2 days and is great sliced cold into kachumbari wraps.',
  'sukuma-ugali': 'Greens keep 2 days; ugali is best fresh but reheats — sprinkle water and steam or microwave covered.',
  'mukimo-beef': 'Both keep 3 days; the stew freezes well. Reheat mukimo with a splash of milk to loosen.',
  'mandazi-chai': 'Mandazi are best day-one; freeze extras and refresh in a hot oven. Chai is best fresh.',
  'kenyan-uji': 'Best fresh; thickens as it sits, so loosen with milk when reheating. Keeps 2 days chilled.',
  'omena-ugali': 'Omena keeps 3 days chilled and reheats well; make the ugali fresh each time.',
  muthokoi: 'Keeps 3 days and freezes 3 months. Reheat with a splash of water; a knob of butter revives it.',
  'ingokho-stew': 'Even better next day — keeps 3 days chilled, freezes 2 months. Flavour deepens overnight.',
  'mursik-sweet-potato': 'Boil sweet potato ahead (keeps 3 days); mursik keeps chilled and sealed for its tang.',
  'nduma-eggs': 'Boil the nduma ahead (keeps 3 days); scramble the eggs fresh to serve.',
  'kenyan-sweet-potato-eggs': 'Boil sweet potato and eggs ahead — both keep 3 days chilled for fast breakfasts.',
  'kenyan-wet-fry-beef': 'Keeps 3 days and freezes 2 months; cook ugali fresh. Reheat the beef with a splash of water.',
  'chapati-beef-stew': 'Chapati keep 3 days wrapped (reheat in a dry pan); the stew freezes 2 months and improves overnight.',
  'chapati-ndengu': 'Ndengu keeps 4 days and freezes 3 months. Make chapati ahead and warm to serve.',
  // Swahili
  'coconut-fish-curry': 'Best day-one (fish is delicate); the sauce keeps 2 days. Reheat gently so it doesn’t split.',
  pilau: 'Keeps 3 days chilled and freezes 2 months. Steam with a splash of water to revive the rice.',
  'mishkaki-skewers': 'Best fresh off the grill. Marinate up to a day ahead; cooked meat keeps 2 days.',
  'maharagwe-nazi': 'Keeps 3 days and freezes beautifully; the coconut beans thicken, so loosen when reheating.',
  'vitumbua-chai': 'Best warm and fresh; the batter can rest overnight in the fridge for a morning cook.',
  'bajia-chutney': 'Best fresh and crisp; refresh leftovers in a hot oven. Chutney keeps a week chilled.',
  'zanzibar-biryani': 'Keeps 3 days and freezes 2 months — biryani is famously good reheated. Steam to revive.',
  'urojo-soup': 'Best fresh; keeps 2 days. Add the crisps and fritters only at serving so they stay crunchy.',
  'mahamri-mbaazi': 'Mahamri are best day-one (freeze and refresh in the oven); mbaazi keeps 3 days and freezes.',
  'viazi-karai': 'Best fresh and crisp; re-crisp leftovers in a hot oven rather than the microwave.',
  'kuku-wa-kupaka': 'Keeps 3 days chilled; reheat the coconut sauce gently. Grill the chicken fresh if you can.',
  // Nigerian
  'jollof-chicken': 'A batch-cook hero — keeps 4 days and freezes 3 months. Day-two jollof is even better.',
  'egusi-soup': 'Keeps 4 days and freezes 3 months; the flavour deepens. Reheat with a splash of water.',
  'efo-riro': 'Even better the next day — keeps 4 days chilled and freezes 3 months.',
  'moi-moi-plantain': 'Moi moi keeps 3 days and freezes well; steam to reheat. Fry plantain fresh.',
  'akara-pap': 'Akara best fresh (refresh in the oven); pap keeps 2 days and reheats with a splash of water.',
  'yam-egg-sauce': 'Sauce keeps 2 days; boil the yam fresh. Reheat the eggs gently so they don’t toughen.',
  'nigerian-fried-yam-eggs': 'Best fresh and crisp; the sauce keeps 2 days. Re-crisp yam in a hot oven.',
  'plantain-frittata': 'Keeps 2 days chilled and is great cold in a lunchbox; reheat gently.',
  'amala-ewedu': 'Ewedu keeps 3 days and freezes; make the amala fresh — it stiffens as it cools.',
  'ofe-nsala': 'Keeps 3 days chilled and freezes 2 months; add the fish back gently when reheating.',
  'tuwo-kuka': 'Kuka soup keeps 3 days and freezes; make the tuwo fresh to serve.',
  'suya-skewers': 'Best fresh and hot. Marinate/spice up to a day ahead; cooked meat keeps 2 days.',
  'ofada-stew': 'The stew keeps 4 days and freezes 3 months — it gets richer. Steam the rice fresh.',
  // Ugandan
  'matoke-groundnut': 'Keeps 3 days chilled; the groundnut sauce thickens, so loosen with water when reheating.',
  'luwombo-chicken': 'Keeps 3 days and freezes 2 months; the slow, rich sauce is even better next day.',
  'beef-posho': 'Stew keeps 3 days and freezes; make posho fresh — reheat with a splash of water if needed.',
  'doodo-groundnut': 'Best within 2 days; reheat gently so the peanut sauce stays creamy.',
  'rolex-wrap': 'Best fresh and warm. Pre-chop the veg the night before for a fast morning rolex.',
  katogo: 'Keeps 2 days chilled; reheat with a splash of stock. A hearty make-ahead breakfast.',
  'eshabwe-kalo': 'Make both fresh — kalo stiffens and the ghee sauce is best warm and just-emulsified.',
  malakwang: 'Keeps 3 days chilled and freezes; the tangy peanut sauce deepens overnight.',
  kabalagala: 'Best day-one; keep 2 days in a tin and refresh briefly in a dry pan.',
  'ugandan-millet-porridge': 'Best fresh; thickens as it sits, so loosen with milk. Keeps 2 days chilled.',
  'ugandan-groundnut-chicken': 'Keeps 3 days and freezes 2 months; loosen the groundnut sauce with stock to reheat.',
  // Indian
  'chicken-tikka': 'Keeps 3 days and freezes 2 months; ideal for meal-prep. The marinade can sit overnight.',
  'chana-masala': 'Keeps 4 days and freezes 3 months — a freezer hero that only gets better.',
  'dal-tadka': 'Keeps 4 days and freezes 3 months; add a fresh tadka when reheating to wake it up.',
  'palak-paneer': 'Keeps 3 days and freezes 2 months; reheat gently to keep the spinach green.',
  'veg-upma': 'Best fresh; keeps 2 days and reheats with a sprinkle of water to steam it soft again.',
  'besan-chilla': 'Best fresh off the griddle; batter keeps a day in the fridge for quick cooking.',
  'sarson-makki': 'Saag keeps 4 days and freezes brilliantly; makki roti is best fresh and warm.',
  'sambar-rice': 'Sambar keeps 4 days and freezes 3 months — famously good reheated. Steam rice fresh.',
  'gujarati-khichdi': 'Best fresh and soft; keeps 2 days. Loosen with water and a little ghee to reheat.',
  'bengali-fish-curry': 'Best day-one; the broth keeps 2 days. Reheat gently so the fish stays whole.',
  'masala-omelette': 'Best straight from the pan. Chop the veg ahead for a 5-minute breakfast.',
  poha: 'Best fresh; keeps a day and reheats with a sprinkle of water. Don’t freeze — it goes mushy.',
  'rajma-rice': 'Keeps 4 days and freezes 3 months; the gravy thickens, so loosen when reheating.',
  // Italian
  'spaghetti-bolognese': 'Ragù keeps 4 days and freezes 3 months — make a double batch. Cook pasta fresh.',
  'pesto-chicken-pasta': 'Best day-one; keeps 2 days. A splash of water and a little fresh pesto revive it.',
  'minestrone-crostini': 'Keeps 4 days and freezes 2 months; it thickens, so loosen with stock when reheating.',
  'chicken-parmigiana': 'Keeps 2 days; reheat in the oven so the crumb re-crisps rather than going soggy.',
  'ricotta-toast': 'Assemble fresh so the toast stays crisp; ricotta keeps a week in the tub.',
  'uova-pomodoro': 'Sauce keeps 3 days and freezes; poach fresh eggs into it when you reheat.',
  'cacio-e-pepe': 'Strictly a make-and-eat dish — the sauce won’t hold. Serve the moment it’s tossed.',
  ribollita: 'Designed to be reheated (that’s the name) — keeps 3 days and deepens; freezes 2 months.',
  'pasta-alla-norma': 'Sauce keeps 3 days and freezes; toss with fresh pasta. The fried eggplant can be made ahead.',
  'pasta-e-fagioli': 'Keeps 3 days and freezes; it thickens as it sits, so loosen with water when reheating.',
  'italian-frittata': 'Keeps 3 days and is excellent cold in a lunchbox; reheat gently or eat at room temperature.',
  'yogurt-granola': 'Assemble fresh so the granola stays crunchy; keep components separate for grab-and-go.',
  'tuna-white-bean-salad': 'Keeps 2 days chilled and the flavour improves — a genuine make-ahead lunch.',
};
for (const [id, s] of Object.entries(STORAGE)) { if (details[id]) details[id].storage = s; }
